//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorize2_Menu
    {
        public int Menu_id { get; set; }
        public string Menu_Name_Th { get; set; }
        public string Menu_Name_En { get; set; }
        public Nullable<int> Menu_Main { get; set; }
        public Nullable<int> Menu_Position { get; set; }
        public string flag_used { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
    }
}
