//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_MASTER
    {
        public int ID { get; set; }
        public string CAR_BRAND { get; set; }
        public string CAR_MODEL { get; set; }
        public string SUB_MODEL { get; set; }
        public string SUB_MODEL2 { get; set; }
        public string SUB_MODEL3 { get; set; }
        public string CAR_MODEL_TEMP { get; set; }
        public string CAR_TYPE { get; set; }
        public string CC { get; set; }
        public string CAR_YEAR { get; set; }
        public string KEYLink_TIRE { get; set; }
        public string KEYLink_BATTERY { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
