//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_arheader
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string docref_no { get; set; }
        public string doc_cancel { get; set; }
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public string pay_doc_no { get; set; }
        public string Expr1 { get; set; }
        public string flag_status { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<double> ar_totalamt { get; set; }
        public string RPA_doc_no { get; set; }
        public string branch_name { get; set; }
        public string BIL_doc_no { get; set; }
    }
}
