//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_cdDetail
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public int line_No { get; set; }
        public string pro_code { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string pro_name { get; set; }
        public string pro_ven_code { get; set; }
        public Nullable<double> store_qty { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<decimal> pro_distotamt { get; set; }
        public Nullable<decimal> pro_amt { get; set; }
        public string pro_code_close { get; set; }
        public string pro_code_cancle { get; set; }
        public string pro_code_cancle_date { get; set; }
        public string cus_code { get; set; }
        public string progroup_code { get; set; }
        public string pro_brand { get; set; }
        public string pro_model { get; set; }
        public Nullable<int> doc_no_run { get; set; }
        public string doc_no_ref { get; set; }
    }
}
