//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_dcDetail
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public int line_No { get; set; }
        public string SN_ID { get; set; }
        public string pro_code { get; set; }
        public string pro_name { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_type { get; set; }
        public string cus_paytype { get; set; }
        public string cus_code { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public Nullable<double> store_qty { get; set; }
        public Nullable<double> pro_costamt { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_amtlasted { get; set; }
        public Nullable<double> pro_disp1 { get; set; }
        public Nullable<double> pro_disp2 { get; set; }
        public Nullable<double> pro_disamt { get; set; }
        public Nullable<double> pro_distotamt { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string doc_candate { get; set; }
        public string io_by { get; set; }
        public int doc_no_run { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string doc_ref_no { get; set; }
        public string pro_code_remark { get; set; }
        public string doc_ref_no_sd { get; set; }
    }
}
