//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_dcHeader
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public Nullable<int> doc_no_run { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_type { get; set; }
        public string cus_paycode { get; set; }
        public string cus_code { get; set; }
        public string member_code { get; set; }
        public Nullable<double> cust_balance { get; set; }
        public string invoice_type { get; set; }
        public Nullable<double> dc_disamt { get; set; }
        public Nullable<double> dc_dispercent { get; set; }
        public Nullable<decimal> dc_distotalamt { get; set; }
        public Nullable<decimal> dc_netamt { get; set; }
        public Nullable<decimal> dc_vatamt { get; set; }
        public Nullable<decimal> dc_totalamt { get; set; }
        public Nullable<double> dc_payamt { get; set; }
        public Nullable<double> dc_paydeposit { get; set; }
        public Nullable<double> dc_paytotal { get; set; }
        public string rec_memo { get; set; }
        public string doc_canmemo { get; set; }
        public Nullable<int> detail_line { get; set; }
        public string pay_date { get; set; }
        public string close_date { get; set; }
        public string close_time { get; set; }
        public Nullable<int> date_report { get; set; }
        public string priceown_code { get; set; }
        public string doc_Close { get; set; }
        public string SEmp_code { get; set; }
        public string vate_type { get; set; }
        public Nullable<decimal> vate_rate { get; set; }
        public string dc_Remark { get; set; }
        public string doc_canceldate { get; set; }
        public Nullable<double> cus_limit { get; set; }
        public string doc_no2 { get; set; }
        public string sEmp_Sale { get; set; }
        public string doc_Cancle { get; set; }
        public string dc_CcRemark { get; set; }
        public string NO_VAT { get; set; }
    }
}
