//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_dsHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_dsHeader()
        {
            this.CS_dsDetail = new HashSet<CS_dsDetail>();
        }
    
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string ven_code { get; set; }
        public string emp_code { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public string doc_cancledate { get; set; }
        public string date_report { get; set; }
        public Nullable<int> detail_line { get; set; }
        public string doc_no2 { get; set; }
        public string sRemark { get; set; }
        public string sCcRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_dsDetail> CS_dsDetail { get; set; }
    }
}
