//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ProCodeNew
    {
        public string branch_no { get; set; }
        public string pro_code_new { get; set; }
        public string pro_code { get; set; }
        public string pro_ven_code { get; set; }
        public string pro_tname { get; set; }
        public string progroup_code { get; set; }
        public string pro_brand_code { get; set; }
        public string pro_model_code { get; set; }
        public string pro_size_code { get; set; }
        public string cStatus { get; set; }
    }
}
