//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_SN
    {
        public string SN { get; set; }
        public string doc_code { get; set; }
        public string sbranch_no { get; set; }
        public string sdate { get; set; }
        public string cflag { get; set; }
    }
}
