//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_sdHeader
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string ven_code { get; set; }
        public string pay_date { get; set; }
        public string emp_code { get; set; }
        public string doc_ref_no1 { get; set; }
        public string doc_Ref_date1 { get; set; }
        public string doc_ref_no2 { get; set; }
        public string doc_Ref_date2 { get; set; }
        public string vate_type { get; set; }
        public Nullable<double> vate_rate { get; set; }
        public Nullable<double> sd_disamt { get; set; }
        public Nullable<double> sd_dispercent { get; set; }
        public Nullable<double> sd_distotalamt { get; set; }
        public Nullable<double> sd_netamt { get; set; }
        public Nullable<double> sd_vatamt { get; set; }
        public Nullable<double> sd_totalamt { get; set; }
        public string sd_Remark { get; set; }
        public string sd_payment { get; set; }
        public Nullable<double> sd_paycash { get; set; }
        public Nullable<double> sd_paycard { get; set; }
        public Nullable<double> sd_paydeposite { get; set; }
        public Nullable<double> sd_payother { get; set; }
        public Nullable<double> sd_paytot { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public string doc_cancledate { get; set; }
        public Nullable<double> ven_limit { get; set; }
        public Nullable<double> ven_balance { get; set; }
        public Nullable<int> date_report { get; set; }
        public Nullable<int> detail_line { get; set; }
        public string doc_no2 { get; set; }
        public string sd_CcRemark { get; set; }
    }
}
