//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_bs_custnew_sb_customer_proprice
    {
        public int auto_id { get; set; }
        public string sale_type { get; set; }
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public string cus_code { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<int> unit_code { get; set; }
        public Nullable<double> sale_percent1 { get; set; }
        public Nullable<double> sale_percent2 { get; set; }
        public Nullable<double> sale_price { get; set; }
        public string start_date { get; set; }
        public string pro_tname { get; set; }
        public string pro_ven_code { get; set; }
        public Nullable<int> type_used_id { get; set; }
        public string stock_status { get; set; }
        public string progroup_code { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public string p_group_name { get; set; }
        public string p_brand_name { get; set; }
        public string p_model_name { get; set; }
        public string p_size_name { get; set; }
        public string p_unit_name { get; set; }
    }
}
