//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_bi_sum_sale
    {
        public string progroup_name { get; set; }
        public string pro_code { get; set; }
        public string pro_tname { get; set; }
        public string pro_brand { get; set; }
        public string pro_model { get; set; }
        public string size_name { get; set; }
        public Nullable<double> tran_qty { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public string Doc_month { get; set; }
        public string year { get; set; }
    }
}
