//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_check_before_ini
    {
        public string branch_no { get; set; }
        public string doc_date { get; set; }
        public string doc_no { get; set; }
        public string pro_code { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string doc_time { get; set; }
        public Nullable<double> move_qty { get; set; }
        public Nullable<double> incre_qty { get; set; }
        public Nullable<double> total_qty { get; set; }
        public Nullable<double> decre_qty { get; set; }
        public Nullable<double> decre_qty_tmp { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<double> pro_price { get; set; }
        public double prv_price { get; set; }
    }
}
