//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_check_bill_type
    {
        public string doc_no { get; set; }
        public string pro_code { get; set; }
        public string pro_stock { get; set; }
        public int FLAG_ITEM { get; set; }
        public int FLAG_SERVICE { get; set; }
    }
}
