//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_data_bill_invoice
    {
        public string doc_no { get; set; }
        public string pro_code { get; set; }
        public int line_no { get; set; }
        public string doc_date { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string cus_code { get; set; }
        public string car_reg { get; set; }
        public string pro_name { get; set; }
        public string progroup_name { get; set; }
        public string pro_brand { get; set; }
        public string pro_Model { get; set; }
        public string pro_size { get; set; }
        public Nullable<double> tran_qty { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_distotamt { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public Nullable<double> Average_Cost { get; set; }
    }
}
