//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_data_incre_detail
    {
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string vat_type { get; set; }
        public string doc_code { get; set; }
        public string pro_code { get; set; }
        public string pro_name { get; set; }
        public string ProGroupName { get; set; }
        public string ProBrand { get; set; }
        public string ProModel { get; set; }
        public string ven_code { get; set; }
        public string VenName { get; set; }
        public int line_no { get; set; }
        public string sale_unit { get; set; }
        public string locat_name { get; set; }
        public Nullable<double> receive_qty { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_disamt { get; set; }
        public Nullable<double> pro_disp1 { get; set; }
        public Nullable<double> pro_disp2 { get; set; }
        public Nullable<double> pro_distotamt { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public Nullable<double> pro_beforevat { get; set; }
        public Nullable<double> pro_incluludevat { get; set; }
        public Nullable<double> pro_amt_recal { get; set; }
        public Nullable<double> total_pro_amt { get; set; }
    }
}
