//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_data_incre_group_apheader
    {
        public string doc_no { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public int doc_no_run { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> receive_qty { get; set; }
        public Nullable<double> pro_distotamt { get; set; }
    }
}
