//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_job_overcrowd
    {
        public Nullable<long> No_ { get; set; }
        public string doc_no { get; set; }
        public string Status { get; set; }
        public string Doc_DayName { get; set; }
        public string Doc_Day { get; set; }
        public string Doc_month { get; set; }
        public string Doc_Year { get; set; }
        public string doc_time { get; set; }
        public string Doc_Time_HH_ { get; set; }
        public string Doc_Date_Close_ { get; set; }
        public string Doc_DayName_Close_ { get; set; }
        public string Doc_Day_Close_ { get; set; }
        public string Doc_month_Close_ { get; set; }
        public string Doc_Year_Close_ { get; set; }
        public string close_time { get; set; }
        public string Doc_Time_Close_HH_ { get; set; }
        public string cus_name { get; set; }
        public string License_Plate { get; set; }
        public string Employee_Name { get; set; }
    }
}
