//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_list_select_product_job
    {
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public Nullable<double> average_cost { get; set; }
        public Nullable<double> pro_ohqty { get; set; }
        public string pro_stock { get; set; }
        public string pro_tname { get; set; }
        public Nullable<double> pro_price_retail { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string pro_ven_code { get; set; }
        public string progroup_code { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public Nullable<double> pro_amtlasted { get; set; }
        public string alternate_code { get; set; }
        public Nullable<double> pro_accqty { get; set; }
        public Nullable<double> pro_otqty { get; set; }
        public Nullable<double> min_qty { get; set; }
        public Nullable<double> ord_qty { get; set; }
        public Nullable<double> max_qty { get; set; }
        public Nullable<double> pro_poqty { get; set; }
        public string stock_status { get; set; }
        public string cancel_date { get; set; }
        public Nullable<int> type_used_id { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> product_group_code { get; set; }
    }
}
