//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_list_select_product_old
    {
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public string pro_tname { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string progroup_code { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public string stock_status { get; set; }
        public Nullable<int> type_used_id { get; set; }
        public string cancel_date { get; set; }
        public string pro_ven_code { get; set; }
        public string subgroup_code { get; set; }
        public string v_group_name { get; set; }
        public string v_brand_name { get; set; }
        public string v_model_name { get; set; }
        public string v_size_name { get; set; }
    }
}
