//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_produce_price
    {
        public string pro_code { get; set; }
        public Nullable<double> pro_price_retail { get; set; }
        public Nullable<double> pro_price_ws { get; set; }
        public string proprice_date { get; set; }
    }
}
