//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_rpt_dot
    {
        public string pro_code { get; set; }
        public string pro_tname { get; set; }
        public Nullable<double> pro_qoh { get; set; }
        public int locat_code { get; set; }
        public string locat_name { get; set; }
        public string dot_name { get; set; }
        public string branch_name { get; set; }
        public string branch_no { get; set; }
        public Nullable<double> lasted_cost { get; set; }
        public Nullable<double> average_cost { get; set; }
        public Nullable<double> pro_ohqty { get; set; }
        public Nullable<double> pro_accqty { get; set; }
        public string progroup_code { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public Nullable<int> pro_size_code { get; set; }
    }
}
