//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_receive_day_sum
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string cus_name { get; set; }
        public Nullable<double> product { get; set; }
        public Nullable<double> Service { get; set; }
        public Nullable<double> Other { get; set; }
    }
}
