//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_rpt_PND54
    {
        public string branch_no { get; set; }
        public string branch_name { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_trog { get; set; }
        public string add_soi { get; set; }
        public string add_road { get; set; }
        public string add_tumbol { get; set; }
        public string add_amphur { get; set; }
        public string prov_name { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string tax_number { get; set; }
        public string doc_no { get; set; }
        public string ven_code { get; set; }
        public string pre_name { get; set; }
        public string ven_name { get; set; }
        public string add_name_b { get; set; }
        public string add_no_b { get; set; }
        public string add_moo_b { get; set; }
        public string add_trog_b { get; set; }
        public string add_soi_b { get; set; }
        public string add_road_b { get; set; }
        public string add_tumbol_b { get; set; }
        public string add_amphur_b { get; set; }
        public Nullable<int> add_provid_b { get; set; }
        public string prov_name_b { get; set; }
        public string add_zip_b { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public string rate_name { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> amt { get; set; }
        public Nullable<double> vatamt { get; set; }
        public Nullable<int> tax_type_id { get; set; }
        public int type_money { get; set; }
        public int count { get; set; }
        public Nullable<int> tax_con_id { get; set; }
        public string tax_id { get; set; }
        public string doc_date { get; set; }
    }
}
