//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_rpt_sale_model
    {
        public string BRANCH_NO { get; set; }
        public string DOC_NO { get; set; }
        public string PRO_CODE { get; set; }
        public Nullable<int> LOCAT_CODE { get; set; }
        public Nullable<double> TRAN_QTY { get; set; }
        public string DATE_REPORT { get; set; }
        public int LINE_NO { get; set; }
    }
}
