//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_rpt_use_promotion_COS
    {
        public Nullable<long> row_id { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public Nullable<int> doc_date_int { get; set; }
        public string doc_time { get; set; }
        public string dealercode { get; set; }
        public string Branch_name { get; set; }
        public string cus_code { get; set; }
        public string custype_code { get; set; }
        public string pre_name { get; set; }
        public string cus_name { get; set; }
        public string campaign_id { get; set; }
        public string campaign_name { get; set; }
        public int pro_group_used_id { get; set; }
        public string pro_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<double> pro_price { get; set; }
        public string pro_start_date { get; set; }
        public Nullable<int> pro_start_date_int { get; set; }
        public string pro_end_date { get; set; }
        public Nullable<int> pro_end_date_int { get; set; }
    }
}
