//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_rp_taxsaleheader_sum_paydoc
    {
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public Nullable<double> total_sum { get; set; }
    }
}
