//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_rpt_paytype
    {
        public string doc_date { get; set; }
        public string pay_date { get; set; }
        public string bank_name { get; set; }
        public string ref_docno { get; set; }
        public string doc_no { get; set; }
        public double cash_amt { get; set; }
        public double doc_payamt { get; set; }
        public double card_amt { get; set; }
        public double chq_payamt { get; set; }
        public double crd_amt { get; set; }
        public double dep_payamt { get; set; }
        public double money_pay { get; set; }
    }
}
