//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_sale_target_mornitoring
    {
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string pro_code { get; set; }
        public string progroup_name { get; set; }
        public string pro_brand { get; set; }
        public string size_name { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public Nullable<double> pro_price { get; set; }
        public string doc_cancel { get; set; }
        public string DATE { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
    }
}
