//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_semp_sale
    {
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string cus_code { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public Nullable<double> car_mileage { get; set; }
        public string docref_no { get; set; }
        public string docref_date { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> ar_amt { get; set; }
        public Nullable<double> ar_disamt { get; set; }
        public Nullable<double> ar_netamt { get; set; }
        public Nullable<double> ar_vatamt { get; set; }
        public Nullable<double> ar_totalamt { get; set; }
        public Nullable<double> ar_payamt { get; set; }
        public Nullable<double> ar_paycash { get; set; }
        public Nullable<double> ar_paycard { get; set; }
        public Nullable<double> ar_paychq { get; set; }
        public Nullable<double> ar_paydeposit { get; set; }
        public Nullable<double> ar_payother { get; set; }
        public Nullable<double> ar_onacccredit { get; set; }
        public Nullable<double> ar_writeup { get; set; }
        public Nullable<double> ar_writeoff { get; set; }
        public Nullable<double> ar_payown { get; set; }
        public Nullable<double> ar_directdebit { get; set; }
        public Nullable<double> ar_paytot { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> sale_id { get; set; }
        public string SEmpNo { get; set; }
        public string stfname { get; set; }
        public string stlname { get; set; }
    }
}
