//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev_union_sum_pay
    {
        public string branch_no { get; set; }
        public string Pay_Name { get; set; }
        public string Pay_code { get; set; }
        public string card_name { get; set; }
        public Nullable<double> total_sum { get; set; }
    }
}
