//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_Transfer_Data
    {
        public int Transfer_ID { get; set; }
        public string Source_Table { get; set; }
        public string Source_Field { get; set; }
        public string Source_Datatype { get; set; }
        public string Source_Key { get; set; }
        public string Destination_DB { get; set; }
        public string Destination_Table { get; set; }
        public string Destination_Field { get; set; }
        public string Destination_Key { get; set; }
        public Nullable<int> Used_Status { get; set; }
        public Nullable<int> Update_Status { get; set; }
        public string send_type { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string WebService_Function { get; set; }
    }
}
