//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string Content { get; set; }
        public string FileName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public byte[] FileContent { get; set; }
        public string Code { get; set; }
        public Nullable<int> DocType { get; set; }
    }
}
