//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_AgeAr
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public string doc_date { get; set; }
        public string cur_date { get; set; }
        public Nullable<int> rdiff { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> credit_bal { get; set; }
        public Nullable<int> credit_term { get; set; }
        public Nullable<double> ar_amt { get; set; }
        public Nullable<int> DATE_REPORT { get; set; }
        public string dealercode { get; set; }
    }
}
