//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_Financial_Detail_Day_End
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_type { get; set; }
        public string cus_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public Nullable<int> line_no { get; set; }
        public string pro_code { get; set; }
        public string pro_name { get; set; }
        public string progroup_code { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public Nullable<int> locat_code { get; set; }
        public Nullable<double> tran_qty { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_disamt { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public Nullable<double> vat_amt { get; set; }
        public Nullable<double> pro_includevat { get; set; }
        public Nullable<double> pro_avgcost { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public Nullable<int> io_by { get; set; }
        public Nullable<int> DATE_REPORT { get; set; }
        public string dealercode { get; set; }
    }
}
