//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_Financial_Header
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string docref_no { get; set; }
        public string docref_date { get; set; }
        public string doc_type { get; set; }
        public string cus_code { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public string payment_duedate { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> total_amt { get; set; }
        public Nullable<double> total_disamt { get; set; }
        public Nullable<double> vat_amt { get; set; }
        public Nullable<double> total_netamt { get; set; }
        public Nullable<double> pay_cash { get; set; }
        public Nullable<double> pay_card { get; set; }
        public Nullable<double> pay_cashcard { get; set; }
        public Nullable<double> pay_chq { get; set; }
        public Nullable<double> pay_deposit { get; set; }
        public Nullable<double> pay_other { get; set; }
        public Nullable<double> pay_total { get; set; }
        public Nullable<int> emp_code { get; set; }
        public Nullable<int> DATE_REPORT { get; set; }
        public Nullable<int> DOCREF_DATE_REPORT { get; set; }
        public string dealercode { get; set; }
    }
}
