//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_SaleAndReceive
    {
        public int doc_no_run { get; set; }
        public Nullable<double> sum_sale_netamt_novat { get; set; }
        public Nullable<double> sum_sale_vatamt { get; set; }
        public Nullable<double> sum_sale_payment { get; set; }
        public Nullable<double> sum_sale_disamt { get; set; }
        public Nullable<double> sumday_sale_money_pay { get; set; }
        public Nullable<double> sum_sale_paycash { get; set; }
        public Nullable<double> sum_sale_paycard { get; set; }
        public Nullable<double> sum_sale_paychq { get; set; }
        public Nullable<double> sum_sale_payother { get; set; }
        public Nullable<double> sum_sale_paydeposit { get; set; }
        public Nullable<double> sum_sale_paypledge { get; set; }
        public Nullable<double> sum_sale_payadd { get; set; }
        public Nullable<double> sum_sale_paytot_rpa { get; set; }
        public Nullable<double> sum_sale_disamt_rpa { get; set; }
        public Nullable<double> sum_sale_directdebit { get; set; }
        public Nullable<double> sum_buy_netamt_novat { get; set; }
        public Nullable<double> sum_buy_vatamt { get; set; }
        public Nullable<double> sum_buy_paycash { get; set; }
        public Nullable<double> sum_buy_paycard { get; set; }
        public Nullable<double> sum_buy_paychq { get; set; }
        public Nullable<double> sum_buy_payother { get; set; }
        public Nullable<double> sum_buy_pay_ppa { get; set; }
        public Nullable<double> sum_buy_money_pay { get; set; }
        public Nullable<double> sum_buy_disall { get; set; }
        public Nullable<double> sum_buy_payadd { get; set; }
        public Nullable<double> sum_day_paytot_rpa { get; set; }
        public Nullable<double> sum_rta { get; set; }
        public Nullable<double> sum_pta { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
