//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_AutoCheck_Set_Head
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> set_gen_id { get; set; }
        public string set_code { get; set; }
        public string set_name { get; set; }
        public string set_startdate { get; set; }
        public string set_enddate { get; set; }
        public string set_cancel { get; set; }
        public Nullable<int> set_startdate_report { get; set; }
        public Nullable<int> set_enddate_report { get; set; }
        public string dealercode { get; set; }
    }
}
