//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_AutoCheck_Set_Detail
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> set_gen_id { get; set; }
        public string set_code { get; set; }
        public Nullable<int> set_check_id { get; set; }
        public Nullable<int> set_line_no { get; set; }
        public string set_product_1 { get; set; }
        public string set_product_2 { get; set; }
        public string set_product_3 { get; set; }
        public Nullable<double> set_price { get; set; }
        public string ck_percent { get; set; }
        public string remark { get; set; }
        public string promotion { get; set; }
        public string dealercode { get; set; }
    }
}
