//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Billing_Log
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string branch_code { get; set; }
        public string branch_name { get; set; }
        public string doc_no { get; set; }
        public string doc_type { get; set; }
        public string doc_code { get; set; }
        public string doc_name { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public Nullable<int> date_report { get; set; }
        public string flag_billing { get; set; }
        public string create_date { get; set; }
        public string create_time { get; set; }
        public Nullable<int> user_create_id { get; set; }
        public string user_create_name { get; set; }
        public string ip_address { get; set; }
        public string Last_Update { get; set; }
        public string flag_net { get; set; }
        public string dealercode { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
    }
}
