//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Branch
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string branch_name { get; set; }
        public string com_name { get; set; }
        public string zone_code { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_trog { get; set; }
        public string add_soi { get; set; }
        public string add_road { get; set; }
        public Nullable<int> add_tumbol_id { get; set; }
        public string add_tumbol { get; set; }
        public Nullable<int> add_amphur_id { get; set; }
        public string add_amphur { get; set; }
        public Nullable<int> add_provid { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string add_fax { get; set; }
        public string tax_number { get; set; }
        public string manager_code { get; set; }
        public string branch_manager { get; set; }
        public string create_product { get; set; }
        public string rec_date { get; set; }
        public string com_engname { get; set; }
        public string add_engname { get; set; }
        public string add_engno { get; set; }
        public string add_engmoo { get; set; }
        public string add_engtrog { get; set; }
        public string add_engsoi { get; set; }
        public string add_engroad { get; set; }
        public string add_engtumbol { get; set; }
        public string add_engamphur { get; set; }
        public string add_engprovince { get; set; }
        public string dealercode { get; set; }
        public string dealer_type { get; set; }
        public string vat_default { get; set; }
        public string authorise_password { get; set; }
        public string e_mail { get; set; }
        public string web_site { get; set; }
        public Nullable<int> client_limit { get; set; }
        public string tax_branch_id { get; set; }
        public string tax_branch { get; set; }
        public string license_key { get; set; }
        public string Vat_DB { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public string branch_used { get; set; }
        public Nullable<int> salezone_id { get; set; }
        public Nullable<int> salegroup_id { get; set; }
        public string flag_hq { get; set; }
        public string POS_ID { get; set; }
        public string TID { get; set; }
        public string pos_id_1 { get; set; }
        public string pos_id_2 { get; set; }
        public string pos_id_3 { get; set; }
        public string sold_to { get; set; }
        public string ship_to { get; set; }
        public string plant_no { get; set; }
        public string MID { get; set; }
        public Nullable<int> POS_ComputerID { get; set; }
        public string connect_vpn { get; set; }
    }
}
