//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_BlueCardRedeemSetting
    {
        public int card_no_run { get; set; }
        public bool BlueCard_exchange_rateby { get; set; }
        public Nullable<int> BlueCard_RewardPoint { get; set; }
        public Nullable<int> BlueCard_Money { get; set; }
        public Nullable<int> BlueCard_MinimumRewardPoint { get; set; }
        public Nullable<double> BlueCard_Ratio_Point { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
    }
}
