//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_BlueCard
    {
        public int card_no_run { get; set; }
        public string IDNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string CardNumber { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public string ReponseCode { get; set; }
        public string ReponseMSG { get; set; }
        public Nullable<decimal> PointsAvailable { get; set; }
        public Nullable<decimal> PointAccureToday { get; set; }
        public string BirthDate { get; set; }
        public string CardStatus { get; set; }
        public string IntegrationKey { get; set; }
        public string MemberStatus { get; set; }
        public string PaymentType { get; set; }
        public string Redeemedpoints { get; set; }
        public string TotalAmount { get; set; }
        public string ProductCode { get; set; }
        public string Qantity { get; set; }
        public string Discount { get; set; }
        public string CouponCode { get; set; }
        public string PINCode { get; set; }
        public string TransectionID { get; set; }
        public string PointsEarnedinTranction { get; set; }
        public string PointsEarnedToday { get; set; }
        public string MemberName { get; set; }
        public string DocNo { get; set; }
        public string Redemption_ID { get; set; }
    }
}
