//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Coupon
    {
        public string coupon_id { get; set; }
        public string coupon_code { get; set; }
        public string coupon_name { get; set; }
        public Nullable<int> coupon_start_number { get; set; }
        public Nullable<int> number_want { get; set; }
        public string coupon_end_date { get; set; }
        public Nullable<bool> used_more_than_once { get; set; }
        public Nullable<bool> allow_coupon { get; set; }
        public string coupon_add_date { get; set; }
        public string coupon_edit_date { get; set; }
        public string coupon_add_time { get; set; }
        public string coupon_edit_time { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> coupon_type_discount { get; set; }
        public Nullable<double> coupon_total_discount { get; set; }
    }
}
