//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Cuscar_Mileage_Job_Log
    {
        public int log_id { get; set; }
        public string branch_no { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public Nullable<int> car_provid { get; set; }
        public string cus_code { get; set; }
        public Nullable<int> car_doc_no_run { get; set; }
        public string job_doc_no { get; set; }
        public Nullable<int> car_bmileage_old { get; set; }
        public Nullable<int> car_bmileage_new { get; set; }
        public Nullable<int> car_mileage_old { get; set; }
        public Nullable<int> car_mileage_new { get; set; }
        public string log_date { get; set; }
        public string log_time { get; set; }
        public string dealercode { get; set; }
    }
}
