//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Cash_Drawer
    {
        public string Cash_Drawer_Code { get; set; }
        public string bankacc_code { get; set; }
        public string Cash_Drawer_Date { get; set; }
        public string Cash_Drawer_Time { get; set; }
        public string DealerCode { get; set; }
        public string SempNo { get; set; }
        public Nullable<double> Cash_Drawer_Balace { get; set; }
        public Nullable<int> Cash_Drawer_Type_ID { get; set; }
        public string Cash_Drawer_Detail { get; set; }
        public string Cash_Drawer_Doc_Ref { get; set; }
        public Nullable<double> Cash_Drawer_Amount { get; set; }
        public string Cash_Drawer_Remark { get; set; }
    }
}
