//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CusCar
    {
        public string branch_no { get; set; }
        public string cus_code { get; set; }
        public string car_chasis { get; set; }
        public string car_reg { get; set; }
        public int car_provid { get; set; }
        public string Car_Code { get; set; }
        public string car_regprovince { get; set; }
        public string car_regdate { get; set; }
        public string car_body { get; set; }
        public string car_engine_cc { get; set; }
        public string car_engine { get; set; }
        public Nullable<int> car_brand_code { get; set; }
        public string car_brand { get; set; }
        public Nullable<int> car_model_code { get; set; }
        public string car_model { get; set; }
        public string car_variant_code { get; set; }
        public string car_variant { get; set; }
        public string car_color { get; set; }
        public string car_year { get; set; }
        public string cartype_code { get; set; }
        public string labour_brand { get; set; }
        public string labour_model { get; set; }
        public string car_guar_code { get; set; }
        public string car_guar_name { get; set; }
        public string car_guar_fdate { get; set; }
        public string car_guar_ldate { get; set; }
        public Nullable<double> car_guar_pay { get; set; }
        public string car_guar_memo { get; set; }
        public string cus_patype { get; set; }
        public string cus_type { get; set; }
        public string cus_name { get; set; }
        public string first_contdate { get; set; }
        public Nullable<int> first_mileage { get; set; }
        public string last_contdate { get; set; }
        public Nullable<int> last_mileage { get; set; }
        public string car_creditlimit { get; set; }
        public string car_creditbalance { get; set; }
        public string cancel_date { get; set; }
        public string rec_memo { get; set; }
        public Nullable<double> Car_Average { get; set; }
        public string car_type1 { get; set; }
        public string icard_number { get; set; }
        public string ICARD_ID { get; set; }
        public string CUS_ID { get; set; }
        public string CUS_CARID { get; set; }
        public string CARD_PASSWORD { get; set; }
        public string REGISTER_DATE { get; set; }
        public string EXPIRE_DATE { get; set; }
        public Nullable<double> POINT_ALL { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public int DOC_NO_RUN { get; set; }
        public string CAR_REG_OLD { get; set; }
        public string ICARD_ID_OLD { get; set; }
        public string WARRANTY_DATE { get; set; }
        public string add_date { get; set; }
        public string edit_date { get; set; }
        public string car_detail1 { get; set; }
        public string car_detail2 { get; set; }
        public string car_detail3 { get; set; }
        public string car_work1 { get; set; }
        public string car_work2 { get; set; }
        public string car_work3 { get; set; }
        public string car_work3_detail { get; set; }
        public string car_work4 { get; set; }
        public string car_work4_detail { get; set; }
        public Nullable<int> Warranty_date_report { get; set; }
        public Nullable<int> CLUB_TYPE { get; set; }
        public string voidno { get; set; }
        public string TB_Customer_type { get; set; }
        public string TB_Customer_code { get; set; }
        public string icard_first_registerdate { get; set; }
        public Nullable<long> add_date_report { get; set; }
        public string pic_cuscar_name { get; set; }
        public string pic_cuscar_path { get; set; }
        public Nullable<int> car_color_id { get; set; }
        public string passkit_serial { get; set; }
        public string passkit_url { get; set; }
        public string passkit_passbookSerial { get; set; }
        public string passkit_shareID { get; set; }
        public string passkit_uniqueID { get; set; }
        public string passkit_register_date { get; set; }
        public string passkit_expire_date { get; set; }
        public string passkit_add_date { get; set; }
        public string passkit_add_time { get; set; }
        public string passkit_edit_date { get; set; }
        public string passkit_edit_time { get; set; }
        public string dealercode { get; set; }
        public string FLAG_NET { get; set; }
        public string Last_Update { get; set; }
        public Nullable<int> gear_id { get; set; }
        public string io { get; set; }
        public string cost_center { get; set; }
        public string pay_vat { get; set; }
        public string car_status { get; set; }
        public string contract_status { get; set; }
        public string pttor_car { get; set; }
    }
}
