//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Chq_Status_Sub
    {
        public string sub_chq_status_id { get; set; }
        public Nullable<int> chq_status_id { get; set; }
        public string sub_chq_status_name { get; set; }
        public string sub_chq_status_used { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
