//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CarVariant
    {
        public string Car_Variant_Code { get; set; }
        public Nullable<int> Car_Brand_Code { get; set; }
        public Nullable<int> Car_Model_Code { get; set; }
        public string Car_Variant { get; set; }
        public string Car_Brand_Codetxt { get; set; }
        public string Car_Model_Codetxt { get; set; }
        public string rec_date { get; set; }
        public string Dealercode { get; set; }
        public string FLAG_NET { get; set; }
        public string Last_Update { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> SendClient { get; set; }
    }
}
