//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CarMaster
    {
        public string Car_Code { get; set; }
        public string Car_Brand_Codetxt { get; set; }
        public string Car_Brand { get; set; }
        public string Car_Model_Codetxt { get; set; }
        public string Car_Model { get; set; }
        public string Car_Variant_Code { get; set; }
        public string Car_Variant { get; set; }
        public string Car_Year_Code { get; set; }
        public Nullable<double> Car_Year { get; set; }
        public string Car_Desc { get; set; }
    }
}
