//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Customer_Contact
    {
        public string branch_no { get; set; }
        public string cus_code { get; set; }
        public string cuscont_code { get; set; }
        public string cuscont_prename { get; set; }
        public string cuscont_name { get; set; }
        public string cuscont_name_eng { get; set; }
        public string cuscont_add_name { get; set; }
        public string cuscont_add_no { get; set; }
        public string cuscont_add_moo { get; set; }
        public string cuscont_add_soi { get; set; }
        public string cuscont_add_trog { get; set; }
        public string cuscont_add_road { get; set; }
        public Nullable<int> cuscont_add_amphur_id { get; set; }
        public string cuscont_add_amphur { get; set; }
        public Nullable<int> cuscont_add_tambol_id { get; set; }
        public string cuscont_add_tumbol { get; set; }
        public Nullable<int> cuscont_add_provid { get; set; }
        public string cuscont_add_province { get; set; }
        public string cuscont_add_zip { get; set; }
        public string cuscont_add_tel { get; set; }
        public string cuscont_add_tel_ext { get; set; }
        public string cuscont_add_tel2 { get; set; }
        public string cuscont_add_tel2_ext { get; set; }
        public string cuscont_add_tel3 { get; set; }
        public string cuscont_add_tel3_ext { get; set; }
        public string cuscont_add_fax { get; set; }
        public string cuscont_add_fax_ext { get; set; }
        public string cuscont_add_mobile { get; set; }
        public string cuscont_add_mobile2 { get; set; }
        public string cuscont_add_email { get; set; }
        public string flag_delete { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public string dealercode { get; set; }
        public string branch_name { get; set; }
        public string icard_id { get; set; }
        public string flag_net { get; set; }
        public string flag_net_tb { get; set; }
        public string last_update { get; set; }
        public string cuscont_tax_id { get; set; }
        public string cuscont_tax_branch_id { get; set; }
        public string cuscont_tax_branch { get; set; }
        public Nullable<int> cuscont_id_address { get; set; }
        public string send_master { get; set; }
    }
}
