//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Custype
    {
        public string custype_code { get; set; }
        public string custype_name { get; set; }
        public string custype_pay { get; set; }
        public string custype_fcode { get; set; }
        public Nullable<int> custype_rundigits { get; set; }
        public string custype_btype { get; set; }
        public string custype_mhq { get; set; }
        public string custype_mbr { get; set; }
        public Nullable<int> cust_discount { get; set; }
        public string Dealercode { get; set; }
        public string FLAG_NET { get; set; }
        public string Last_Update { get; set; }
        public string branch_no { get; set; }
    }
}
