//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Customer
    {
        public string branch_no { get; set; }
        public string cus_code { get; set; }
        public int Cus_code_run { get; set; }
        public string cus_type { get; set; }
        public string custype_code { get; set; }
        public string buss_code { get; set; }
        public string cus_paytype { get; set; }
        public string pre_name { get; set; }
        public string cus_name { get; set; }
        public string cuscont_name { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_soi { get; set; }
        public string add_trog { get; set; }
        public string add_road { get; set; }
        public string add_tumbol { get; set; }
        public string add_amphur { get; set; }
        public Nullable<int> add_provid { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string add_fax { get; set; }
        public string add_email { get; set; }
        public string cusgroup_code { get; set; }
        public string cus_member { get; set; }
        public Nullable<double> pro_discount { get; set; }
        public Nullable<double> lab_discount { get; set; }
        public Nullable<double> cust_discount { get; set; }
        public Nullable<int> vat_code { get; set; }
        public Nullable<double> pay_method { get; set; }
        public Nullable<double> credit_term_code { get; set; }
        public Nullable<double> credit_term { get; set; }
        public Nullable<double> credit_limit { get; set; }
        public Nullable<double> credit_bal { get; set; }
        public string contact_fdate { get; set; }
        public string contact_ldate { get; set; }
        public string cancel_date { get; set; }
        public string behavior_memo { get; set; }
        public string rec_memo { get; set; }
        public string on_acccredit { get; set; }
        public string cus_birth { get; set; }
        public string cus_sex { get; set; }
        public string discount_type { get; set; }
        public string deposit_amount { get; set; }
        public string add_mobile { get; set; }
        public string AF_Status { get; set; }
        public string card_number { get; set; }
        public string registration_number { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public string add_date { get; set; }
        public string edit_date { get; set; }
        public string cuscont_name_eng { get; set; }
        public string work_company { get; set; }
        public string work_type1 { get; set; }
        public string work_type2 { get; set; }
        public string work_type3 { get; set; }
        public string work_type4 { get; set; }
        public string work_type5 { get; set; }
        public string work_type5_detail { get; set; }
        public string work_position { get; set; }
        public string work_section { get; set; }
        public string work_tower { get; set; }
        public string work_floor { get; set; }
        public string work_no { get; set; }
        public string work_soi { get; set; }
        public string work_road { get; set; }
        public string work_tumbol { get; set; }
        public string work_amphur { get; set; }
        public Nullable<int> work_provid { get; set; }
        public string work_province { get; set; }
        public string work_zipcode { get; set; }
        public string work_phone { get; set; }
        public string work_phone2 { get; set; }
        public string work_fax { get; set; }
        public string work_email { get; set; }
        public string type_newsletter1 { get; set; }
        public string type_newsletter2 { get; set; }
        public string type_newsletter3 { get; set; }
        public string type_newsletter4 { get; set; }
        public string type_newsletter5 { get; set; }
        public Nullable<int> add_tambol_id { get; set; }
        public Nullable<int> add_amphur_id { get; set; }
        public Nullable<int> work_tambol_id { get; set; }
        public Nullable<int> work_amphur_id { get; set; }
        public string add_tel_ext { get; set; }
        public string add_tel2 { get; set; }
        public string add_tel2_ext { get; set; }
        public string add_tel3 { get; set; }
        public string add_tel3_ext { get; set; }
        public string add_fax_ext { get; set; }
        public string add_mobile2 { get; set; }
        public string work_moo { get; set; }
        public string work_trog { get; set; }
        public string work_fax2 { get; set; }
        public string work_phone3 { get; set; }
        public string work_phone4 { get; set; }
        public string work_mobile { get; set; }
        public string work_mobile2 { get; set; }
        public Nullable<int> FLAG_UPDATE_PROV { get; set; }
        public string TB_Customer_type { get; set; }
        public string TB_Customer_code { get; set; }
        public string cuscont_add_name { get; set; }
        public string cuscont_add_no { get; set; }
        public string cuscont_add_moo { get; set; }
        public string cuscont_add_soi { get; set; }
        public string cuscont_add_trog { get; set; }
        public string cuscont_add_road { get; set; }
        public Nullable<int> cuscont_add_amphur_id { get; set; }
        public string cuscont_add_amphur { get; set; }
        public Nullable<int> cuscont_add_tambol_id { get; set; }
        public string cuscont_add_tumbol { get; set; }
        public Nullable<int> cuscont_add_provid { get; set; }
        public string cuscont_add_province { get; set; }
        public string cuscont_add_zip { get; set; }
        public string cuscont_add_tel { get; set; }
        public string cuscont_add_tel_ext { get; set; }
        public string cuscont_add_tel2 { get; set; }
        public string cuscont_add_tel2_ext { get; set; }
        public string cuscont_add_tel3 { get; set; }
        public string cuscont_add_tel3_ext { get; set; }
        public string cuscont_add_fax { get; set; }
        public string cuscont_add_fax_ext { get; set; }
        public string cuscont_add_mobile { get; set; }
        public string cuscont_add_mobile2 { get; set; }
        public string cuscont_add_email { get; set; }
        public Nullable<double> credit_bal_cs { get; set; }
        public string tax_id { get; set; }
        public string tax_branch_id { get; set; }
        public string cuscont_tax_id { get; set; }
        public string cuscont_tax_branch_id { get; set; }
        public string tax_branch { get; set; }
        public string cuscont_tax_branch { get; set; }
        public string cus_name_trim { get; set; }
        public string address_trim { get; set; }
        public string pic_customer_name { get; set; }
        public string pic_customer_path { get; set; }
        public Nullable<int> id_address { get; set; }
        public Nullable<int> work_id_address { get; set; }
        public Nullable<int> cuscont_id_address { get; set; }
        public Nullable<int> old_add_prov_id { get; set; }
        public Nullable<int> old_add_tambol_id { get; set; }
        public Nullable<int> old_add_amphur_id { get; set; }
        public Nullable<int> old_work_provid { get; set; }
        public Nullable<int> old_work_tambol_id { get; set; }
        public Nullable<int> old_work_amphur_id { get; set; }
        public Nullable<int> old_cuscont_add_provid { get; set; }
        public Nullable<int> old_cuscont_add_tambol_id { get; set; }
        public Nullable<int> old_cuscont_add_amphur_id { get; set; }
        public Nullable<int> sale_user_id { get; set; }
        public Nullable<int> flag_up_address { get; set; }
        public string flag_cus_mobile { get; set; }
        public string dealercode { get; set; }
        public string FLAG_NET { get; set; }
        public string Last_Update { get; set; }
        public string chq_day_receive { get; set; }
        public string day_bill_pay { get; set; }
        public string rpt_tmp_sale_price_show { get; set; }
        public string check_credit_total { get; set; }
        public string cus_member_id { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string sap_number { get; set; }
    }
}
