//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Customer_Proprice
    {
        public int auto_id { get; set; }
        public string branch_no { get; set; }
        public string cus_code { get; set; }
        public string sale_type { get; set; }
        public string pro_code { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> sale_percent1 { get; set; }
        public Nullable<double> sale_percent2 { get; set; }
        public Nullable<double> sale_price { get; set; }
        public string start_date { get; set; }
        public Nullable<int> start_date_int { get; set; }
        public Nullable<int> unit_code { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string dealercode { get; set; }
    }
}
