//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Dealercode_Master
    {
        public string dealercode { get; set; }
        public string DealerName { get; set; }
        public string Dealertype { get; set; }
        public string ip_address { get; set; }
        public string ip_address_pub { get; set; }
        public string http_path { get; set; }
        public Nullable<int> salezone_id { get; set; }
        public Nullable<int> salegroup_id { get; set; }
        public string branch_no { get; set; }
        public string http_client_webservices { get; set; }
        public string flag_used { get; set; }
        public string dealercode_sap { get; set; }
        public Nullable<int> NEXTSERVICE_SENDCLIENT { get; set; }
        public Nullable<int> MAIN_NEXTSERVICE_SENDCLIENT { get; set; }
    }
}
