//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_ExtraDiscount
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Percents { get; set; }
        public string ProgroupCode { get; set; }
        public string CustypeCode { get; set; }
        public Nullable<int> RankNo { get; set; }
        public Nullable<double> Baht { get; set; }
        public string Code { get; set; }
        public bool IsDelete { get; set; }
        public string ExDiscountStartDate { get; set; }
        public string ExDiscountEndDate { get; set; }
    }
}
