//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_FilmCar_Detail_Temp
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> film_gen_id { get; set; }
        public string film_code { get; set; }
        public string film_pro_code { get; set; }
        public Nullable<int> film_line_no { get; set; }
        public Nullable<double> film_pro_price { get; set; }
        public Nullable<double> film_pro_distot { get; set; }
        public Nullable<double> film_pro_incretot { get; set; }
        public string dealercode { get; set; }
    }
}
