//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_FilmCar_Header
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> film_gen_id { get; set; }
        public string film_typesale { get; set; }
        public string film_code { get; set; }
        public string film_name { get; set; }
        public string film_startdate { get; set; }
        public string film_enddate { get; set; }
        public string film_cancel { get; set; }
        public string film_main_pro_code { get; set; }
        public Nullable<double> film_main_pro_price { get; set; }
        public Nullable<int> film_startdate_report { get; set; }
        public Nullable<int> film_enddate_report { get; set; }
        public string film_add_date { get; set; }
        public string film_add_time { get; set; }
        public string film_edit_date { get; set; }
        public string film_edit_time { get; set; }
        public Nullable<int> film_user_add { get; set; }
        public Nullable<int> film_user_edit { get; set; }
        public string dealercode { get; set; }
    }
}
