//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LocatLinkDot
    {
        public int locat_code { get; set; }
        public int dot_id { get; set; }
        public string dealercode { get; set; }
        public string remark { get; set; }
    }
}
