//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_meeting
    {
        public int doc_run { get; set; }
        public string MEETING_ID { get; set; }
        public string doc_job_ref_no { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string car_reg { get; set; }
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public string tel { get; set; }
        public string head { get; set; }
        public string detail { get; set; }
        public string MEETING_STATUS { get; set; }
        public string DATE2 { get; set; }
        public string TIME2 { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public string car_chasis { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string time3 { get; set; }
    }
}
