//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Prolocation
    {
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public int locat_code { get; set; }
        public string location_code { get; set; }
        public Nullable<double> pro_qoh { get; set; }
        public string novat_status { get; set; }
        public Nullable<double> pro_qoh_export { get; set; }
        public string dealercode { get; set; }
    }
}
