//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_ProSize
    {
        public int pro_size_code { get; set; }
        public string size_name { get; set; }
        public string pro_size { get; set; }
        public string size1 { get; set; }
        public string size2 { get; set; }
        public string size3 { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public string pro_size_code_SAP { get; set; }
    }
}
