//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Product_Replace
    {
        public int id { get; set; }
        public string branch_no { get; set; }
        public string pro_code_old { get; set; }
        public string pro_code_new { get; set; }
        public string transfer_option { get; set; }
        public string sUserName { get; set; }
        public string ip_address { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string dealercode { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
    }
}
