//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Product_Set_Head
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> ps_gen_id { get; set; }
        public string ps_typesale { get; set; }
        public string ps_code { get; set; }
        public string ps_name { get; set; }
        public string ps_startdate { get; set; }
        public string ps_enddate { get; set; }
        public string ps_cancel { get; set; }
        public Nullable<int> ps_startdate_report { get; set; }
        public Nullable<int> ps_enddate_report { get; set; }
        public string dealercode { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public Nullable<int> pro_price_set { get; set; }
        public string include_with_promotion { get; set; }
    }
}
