//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Product_Temp_Delete
    {
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public string pro_ven_code { get; set; }
        public string alternate_code { get; set; }
        public string subgroup_code { get; set; }
        public string ven_code { get; set; }
        public string pro_recordtype { get; set; }
        public string pro_tname { get; set; }
        public string pro_ename { get; set; }
        public string pro_type { get; set; }
        public string progroup_code { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public string pro_brand { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public string pro_model { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public string pro_size { get; set; }
        public string pro_stock { get; set; }
        public Nullable<int> store_unit_code { get; set; }
        public string store_unit { get; set; }
        public Nullable<int> buy_unit_code { get; set; }
        public string buy_unit { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string sale_unit { get; set; }
        public Nullable<double> max_qty { get; set; }
        public Nullable<double> ord_qty { get; set; }
        public Nullable<double> min_qty { get; set; }
        public Nullable<double> lasted_cost { get; set; }
        public Nullable<double> average_cost { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string store_location { get; set; }
        public Nullable<double> pro_ohqty { get; set; }
        public Nullable<double> pro_accqty { get; set; }
        public Nullable<double> pro_poqty { get; set; }
        public Nullable<double> pro_ocqty { get; set; }
        public Nullable<double> pro_otqty { get; set; }
        public Nullable<double> pro_bqty { get; set; }
        public Nullable<double> pro_amtavg { get; set; }
        public Nullable<double> pro_amtfifo { get; set; }
        public Nullable<double> pro_amtlasted { get; set; }
        public Nullable<double> pro_disc { get; set; }
        public Nullable<double> pro_price_retail { get; set; }
        public Nullable<double> pro_price_ws { get; set; }
        public Nullable<double> pro_price_buy { get; set; }
        public Nullable<double> pro_invat { get; set; }
        public string cancel_date { get; set; }
        public string pro_cantype { get; set; }
        public string stock_status { get; set; }
        public string rec_date { get; set; }
        public string rec_memo { get; set; }
        public string tpe_package { get; set; }
        public int Pro_Code_Run { get; set; }
        public string AF_Status { get; set; }
        public Nullable<double> SCARD_TYPE { get; set; }
        public string SUB_NEXTSERV_CODE { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<double> SER_DAY { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<double> Average_Cost_VAT { get; set; }
        public Nullable<double> Average_Cost_NOVAT { get; set; }
        public Nullable<double> LASTED_COST_VAT { get; set; }
        public string TB_Status { get; set; }
        public string EU_Status { get; set; }
        public Nullable<double> EU_Point { get; set; }
        public string TOP_Status { get; set; }
        public Nullable<double> TOP_Point { get; set; }
        public string lasted_cost_date { get; set; }
        public Nullable<double> pro_ohqty_cs { get; set; }
        public Nullable<double> pro_qoh_cs { get; set; }
        public Nullable<double> pro_accqty_export { get; set; }
        public Nullable<double> pro_otqty_export { get; set; }
        public Nullable<double> pro_ohqty_export { get; set; }
        public Nullable<double> average_cost_export { get; set; }
        public Nullable<double> lasted_cost_export { get; set; }
        public string dash_board_progroup { get; set; }
        public string dash_board_progroup_2 { get; set; }
        public string dealercode { get; set; }
        public string product_type_service { get; set; }
        public Nullable<int> type_used_id { get; set; }
        public string flag_fast_product { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
    }
}
