//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Progroup
    {
        public string progroup_code { get; set; }
        public Nullable<int> product_group_code { get; set; }
        public string progroup_name { get; set; }
        public Nullable<double> progroup_guarantee { get; set; }
        public string AF_Status { get; set; }
        public Nullable<double> scard_type { get; set; }
        public string Progroup_Type { get; set; }
        public string Default_CS { get; set; }
        public string progroup_name_en { get; set; }
        public string type_package { get; set; }
        public Nullable<double> scard_type_mobile { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public Nullable<int> SendClient { get; set; }
        public string progroup_code_SAP { get; set; }
    }
}
