//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_promo
    {
        public string pm_code { get; set; }
        public string pm_name { get; set; }
        public string pm_startdate { get; set; }
        public string pm_enddate { get; set; }
        public string progroup_code { get; set; }
        public string pm_model { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public string pro_brand { get; set; }
        public string pro_type { get; set; }
        public string pro_code { get; set; }
        public string pm_cond { get; set; }
        public string free_cond { get; set; }
        public string pm_by { get; set; }
        public Nullable<int> pm_byminqty { get; set; }
        public Nullable<int> pm_bymaxqty { get; set; }
        public Nullable<double> pm_byminamt { get; set; }
        public Nullable<double> pm_bymaxamt { get; set; }
        public string pm_promotetype { get; set; }
        public string pm_prodtype { get; set; }
        public string pm_product { get; set; }
        public string pm_prodchoice { get; set; }
        public string pm_progroup { get; set; }
        public string pm_probrand { get; set; }
        public string pm_promodel { get; set; }
        public Nullable<double> pm_qty { get; set; }
        public Nullable<double> pm_amt { get; set; }
        public Nullable<double> pm_discpercent { get; set; }
        public Nullable<double> pm_discbaht { get; set; }
        public string pm_branch { get; set; }
        public string pm_cancel { get; set; }
        public string pm_remark { get; set; }
        public string pm_type { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
