//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_PromotionDetail
    {
        public int doc_no_run { get; set; }
        public string pro_id { get; set; }
        public string product_group_code { get; set; }
        public string progroup_code { get; set; }
        public string pro_brand_code { get; set; }
        public string pro_model_code { get; set; }
        public string pro_size_code { get; set; }
        public Nullable<double> pro_discount_rate_special { get; set; }
        public string pro_discount_unit_special { get; set; }
        public Nullable<bool> status_give_product { get; set; }
        public string pro_code_show { get; set; }
        public string pro_code { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    
        public virtual SB_PromotionHeader SB_PromotionHeader { get; set; }
    }
}
