//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_paytype
    {
        public string pay_code { get; set; }
        public string pay_name { get; set; }
        public string pay_date { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string SAP_pay_type { get; set; }
        public string sold_to { get; set; }
        public string ship_to { get; set; }
    }
}
