//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Product_Set_Temp
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public Nullable<int> ps_gen_id { get; set; }
        public string ps_code { get; set; }
        public string ps_pro_code { get; set; }
        public Nullable<int> ps_line_no { get; set; }
        public Nullable<int> ps_locat_code { get; set; }
        public Nullable<double> ps_qty { get; set; }
        public Nullable<double> ps_price { get; set; }
        public string dealercode { get; set; }
    }
}
