//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_proprice
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public string proprice_date { get; set; }
        public string cus_groupcode { get; set; }
        public string dealercode { get; set; }
        public Nullable<double> pro_price_retail { get; set; }
        public Nullable<double> pro_price_ws { get; set; }
        public Nullable<int> unit_code { get; set; }
        public string unit_name { get; set; }
        public Nullable<double> pro_discpercent { get; set; }
        public Nullable<double> pro_discount { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
