//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_PROSUB_NEXTSERV
    {
        public Nullable<double> SCARD_TYPE { get; set; }
        public string SUB_NEXTSERV_CODE { get; set; }
        public string SUB_NEXTSERV_Name { get; set; }
        public string PROGROUP_CODE { get; set; }
        public Nullable<double> Km { get; set; }
        public Nullable<double> Ser_day { get; set; }
        public Nullable<double> LOOP { get; set; }
        public string Link { get; set; }
        public string Link1 { get; set; }
        public string Link2 { get; set; }
        public int doc_no_run { get; set; }
        public string Dealercode { get; set; }
        public string Branch_no { get; set; }
        public string Branch_name { get; set; }
        public string FLAG_NET { get; set; }
        public string Last_Update { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public Nullable<int> SendClient { get; set; }
    }
}
