//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_PromotionHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SB_PromotionHeader()
        {
            this.SB_PromotionDetail = new HashSet<SB_PromotionDetail>();
        }
    
        public string pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_start_date { get; set; }
        public string pro_start_time { get; set; }
        public string pro_end_date { get; set; }
        public string pro_end_time { get; set; }
        public string campaign_id { get; set; }
        public Nullable<int> pro_condition_time_id { get; set; }
        public string pro_condition_time_detail { get; set; }
        public Nullable<bool> allow_muti_promotion { get; set; }
        public Nullable<bool> allow_muti_voucher { get; set; }
        public Nullable<bool> required_coupon_code { get; set; }
        public Nullable<bool> allow_promotion { get; set; }
        public string pro_add_date { get; set; }
        public string pro_add_time { get; set; }
        public string pro_edit_date { get; set; }
        public string pro_edit_time { get; set; }
        public Nullable<int> pro_group_used_id { get; set; }
        public string pro_group_used_detail { get; set; }
        public Nullable<int> pro_type_id { get; set; }
        public Nullable<double> pro_type_detail { get; set; }
        public Nullable<int> pro_price_id { get; set; }
        public Nullable<double> pro_price_total { get; set; }
        public Nullable<int> pro_give_type_id { get; set; }
        public Nullable<int> pro_give_type_detail { get; set; }
        public Nullable<bool> pro_give_product_same { get; set; }
        public Nullable<bool> pro_give_same_buy { get; set; }
        public Nullable<int> pro_discount_id { get; set; }
        public Nullable<double> pro_discount_num { get; set; }
        public Nullable<double> pro_discount_rate { get; set; }
        public string pro_discount_unit { get; set; }
        public string rate_price_cal { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string pro_condition_time_start { get; set; }
        public string pro_condition_time_end { get; set; }
        public string coupon_id { get; set; }
        public string branch_no_list { get; set; }
        public int pro_give_free_amount { get; set; }
        public Nullable<int> group_coupon_id { get; set; }
        public string allow_muti_promotion_detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SB_PromotionDetail> SB_PromotionDetail { get; set; }
    }
}
