//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_PROSUB_NEXTSERV_CAR
    {
        public string prosub_code { get; set; }
        public string SUB_NEXTSERV_Name { get; set; }
        public string SUB_NEXTSERV_Code { get; set; }
        public Nullable<double> Km { get; set; }
        public Nullable<double> Ser_day { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
