//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Probrand
    {
        public int pro_brand_code { get; set; }
        public string pro_brand { get; set; }
        public string progroup_code { get; set; }
        public string WARRANTY_STATUS { get; set; }
        public string pro_brand_short { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public string pro_brand_code_SAP { get; set; }
    }
}
