//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_SeeCar
    {
        public int id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string version { get; set; }
        public string year { get; set; }
        public string f_marking { get; set; }
        public string f_lb { get; set; }
        public string r_marking { get; set; }
        public string r_lb { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
