//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Time_Sell_Product
    {
        public int id { get; set; }
        public string pro_product_code { get; set; }
        public string pro_product_group_code { get; set; }
        public string pro_sell_week { get; set; }
        public string pro_sell_day { get; set; }
        public Nullable<System.TimeSpan> pro_sell_time_start { get; set; }
        public Nullable<System.TimeSpan> pro_sell_time_end { get; set; }
        public string probrand { get; set; }
        public string promodel { get; set; }
        public Nullable<int> SendClient { get; set; }
    }
}
