//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_TextReport
    {
        public int auto_id { get; set; }
        public string text_id { get; set; }
        public string text_position { get; set; }
        public string text_document { get; set; }
        public string text_report { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
