//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Vote
    {
        public int id { get; set; }
        public int vote_id { get; set; }
        public string vote_name { get; set; }
        public Nullable<int> vote_active { get; set; }
        public string vote_choice_type { get; set; }
        public string vote_start { get; set; }
        public string vote_end { get; set; }
        public Nullable<int> vote_multi { get; set; }
        public string vote_multi_time { get; set; }
        public Nullable<int> vote_random { get; set; }
        public Nullable<int> vote_order { get; set; }
        public string vote_date { get; set; }
        public string vote_time { get; set; }
        public Nullable<double> date_report { get; set; }
        public Nullable<int> vote_used { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
