//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Vendor_Temp_Delete
    {
        public string branch_no { get; set; }
        public string ven_code { get; set; }
        public int ven_code_run { get; set; }
        public string pre_name { get; set; }
        public string ven_name { get; set; }
        public string contact_name { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_soi { get; set; }
        public string add_trog { get; set; }
        public string add_road { get; set; }
        public string add_tumbol { get; set; }
        public string add_amphur { get; set; }
        public Nullable<int> add_provid { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string add_fax { get; set; }
        public string add_email { get; set; }
        public string vengroup_code { get; set; }
        public string vat_type { get; set; }
        public string vat_code { get; set; }
        public Nullable<double> ven_discount { get; set; }
        public Nullable<int> ven_ship_term { get; set; }
        public string ven_ct_code { get; set; }
        public Nullable<int> ven_credit_term { get; set; }
        public Nullable<double> ven_credit_limit { get; set; }
        public Nullable<double> ven_balance { get; set; }
        public string contact_fdate { get; set; }
        public string contact_ldate { get; set; }
        public string cancel_date { get; set; }
        public string rec_memo { get; set; }
        public Nullable<int> ordering_date { get; set; }
        public Nullable<int> ordering_cycle { get; set; }
        public string AF_Status { get; set; }
        public Nullable<double> ven_balance_cs { get; set; }
        public string tax_id { get; set; }
        public string tax_branch_id { get; set; }
        public string tax_branch { get; set; }
        public string dealercode { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
    }
}
