//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBHRUser
    {
        public int user_id { get; set; }
        public string SEmpNo { get; set; }
        public string branch_no { get; set; }
        public string ip_address { get; set; }
        public string susername { get; set; }
        public string spassword { get; set; }
        public string stfname { get; set; }
        public string stlname { get; set; }
        public string sefname { get; set; }
        public string selname { get; set; }
        public string clevel { get; set; }
        public string dbirthday { get; set; }
        public string sauthor { get; set; }
        public string card_id { get; set; }
        public string card_start_date { get; set; }
        public string card_end_date { get; set; }
        public string card_place { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_soi { get; set; }
        public string add_trog { get; set; }
        public string add_road { get; set; }
        public string add_tumbol { get; set; }
        public string add_amphur { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string add_fax { get; set; }
        public string add_email { get; set; }
        public string emp_position { get; set; }
        public string start_date { get; set; }
        public string resign_date { get; set; }
        public string emp_status { get; set; }
        public string rec_memo { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<double> sale_credit_limit { get; set; }
        public string used_icard { get; set; }
        public string used_pay_cancel { get; set; }
        public string used_pay_confirm { get; set; }
        public string used_revenue { get; set; }
        public string used_rpa_save { get; set; }
        public string used_product_data { get; set; }
        public string used_history_sale { get; set; }
        public string used_groove_price { get; set; }
        public string used_movement { get; set; }
        public string used_ap { get; set; }
        public string used_vendor { get; set; }
        public string used_product_cost { get; set; }
        public string used_rpa_temp { get; set; }
        public string used_price_edit { get; set; }
        public string used_po_incre { get; set; }
        public string used_sale_percent1_edit { get; set; }
        public string used_sale_percent2_edit { get; set; }
        public string used_sale_price_edit { get; set; }
        public string used_pay_tmp { get; set; }
        public string used_pay_ino { get; set; }
        public string used_pay_tmw { get; set; }
        public string used_pay_inv { get; set; }
        public string used_pay_rda { get; set; }
        public string used_pay_rpa { get; set; }
        public string used_pay_rta { get; set; }
        public string used_pay_ppa { get; set; }
        public string used_pay_pta { get; set; }
        public string used_sst { get; set; }
        public string used_docno_ref { get; set; }
        public string used_pay_cancel_spilt_bill { get; set; }
        public string used_passkit { get; set; }
        public string used_product_cost_r { get; set; }
        public string used_product_cost_w { get; set; }
        public string used_pay_abb { get; set; }
        public string used_system { get; set; }
        public string nickname { get; set; }
        public string blood { get; set; }
        public Nullable<int> add_tambol_id { get; set; }
        public Nullable<int> add_amphur_id { get; set; }
        public Nullable<int> add_provid { get; set; }
        public Nullable<int> salezone_id { get; set; }
        public Nullable<int> salegroup_id { get; set; }
        public string add_mobile { get; set; }
        public string user_salary { get; set; }
        public string user_salary_perday { get; set; }
        public string user_pic_name { get; set; }
        public string user_pic_path { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public Nullable<int> edit_user_id { get; set; }
        public Nullable<double> sale_percent1 { get; set; }
        public Nullable<double> sale_percent2 { get; set; }
        public Nullable<double> sale_price { get; set; }
        public Nullable<double> sale_all_bill { get; set; }
        public string used_edit_car_mileage { get; set; }
        public string dealercode { get; set; }
        public string used_under_stock { get; set; }
        public string emp_id { get; set; }
        public string check_expire_user { get; set; }
        public string user_expire_date { get; set; }
    }
}
