//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBQty
    {
        public string ssecno { get; set; }
        public string FStoreID { get; set; }
        public Nullable<int> FQty { get; set; }
        public string edtdate { get; set; }
        public string pstatus { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
