//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBQty0000
    {
        public string ssecno { get; set; }
        public string FStoreID { get; set; }
        public System.DateTime Invdate { get; set; }
        public Nullable<double> FQty { get; set; }
        public Nullable<decimal> Funitprice { get; set; }
        public string pstatus { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
