//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbqty_change
    {
        public int change_id { get; set; }
        public string fstoreid { get; set; }
        public string ssecno { get; set; }
        public string date_change { get; set; }
        public string date_change_since { get; set; }
        public Nullable<int> old_qty { get; set; }
        public Nullable<int> new_qty { get; set; }
        public string remark { get; set; }
        public string sempno { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
