//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBSale_Temp
    {
        public string ssaleid { get; set; }
        public string ssecno { get; set; }
        public string FStoreID { get; set; }
        public string FSTOREDETAIL { get; set; }
        public Nullable<int> FQty { get; set; }
        public Nullable<double> FUNITPRICE { get; set; }
        public Nullable<double> FPrice { get; set; }
        public string saledate { get; set; }
        public string saletype { get; set; }
        public string salecash { get; set; }
        public string SMemo { get; set; }
        public string barcodeid { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
