//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBSale_Head
    {
        public string SSaleID { get; set; }
        public string Scompno { get; set; }
        public string SDeparno { get; set; }
        public string SSecno { get; set; }
        public string sale_type { get; set; }
        public string cash_type { get; set; }
        public Nullable<int> change_money { get; set; }
        public string DSaleDATE { get; set; }
        public string DSaleTime { get; set; }
        public string SaleRef { get; set; }
        public string FREQUESTDATE { get; set; }
        public string SEmpno { get; set; }
        public string SCust { get; set; }
        public string FPLACE { get; set; }
        public string ssaleno { get; set; }
        public string crd_fname { get; set; }
        public string crd_sname { get; set; }
        public string crd_number { get; set; }
        public string crd_bank { get; set; }
        public string crd_type { get; set; }
        public string sale_status { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
