//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBSale_Head_Prn
    {
        public string SSaleID { get; set; }
        public string Scompno { get; set; }
        public string SDeparno { get; set; }
        public string SSecno { get; set; }
        public string Sale_type { get; set; }
        public string Cash_type { get; set; }
        public Nullable<decimal> Change_money { get; set; }
        public string Dsaledate { get; set; }
        public string Dsaletime { get; set; }
        public string SaleRef { get; set; }
        public string FRequestdate { get; set; }
        public string Sempno { get; set; }
        public string SCust { get; set; }
        public string Fplace { get; set; }
        public string SSaleno { get; set; }
        public string crd_fname { get; set; }
        public string crd_sname { get; set; }
        public string crd_number { get; set; }
        public string crd_bank { get; set; }
        public string crd_type { get; set; }
        public string sale_status { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
