//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Apdocno
    {
        public int id { get; set; }
        public string doc_no { get; set; }
        public string doc_no_temp { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string doc_code { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
