//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Ar_Payment_Temp_Web_Log
    {
        public int id { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public Nullable<double> num_of_pay { get; set; }
        public string type_pay { get; set; }
        public string flag_delete { get; set; }
        public string delete_date { get; set; }
        public string delete_time { get; set; }
        public string dealercode { get; set; }
        public string web_log_send_to { get; set; }
        public Nullable<int> web_log_user_id { get; set; }
        public string web_log_date { get; set; }
        public string web_log_time { get; set; }
        public Nullable<int> web_log_flag_send { get; set; }
        public string web_log_message { get; set; }
    }
}
