//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_avg_cal
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string pro_code { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string doc_code { get; set; }
        public string cus_code { get; set; }
        public Nullable<double> move_qty { get; set; }
        public Nullable<double> incre_qty { get; set; }
        public Nullable<double> decre_qty { get; set; }
        public Nullable<double> decre_qty_tmp { get; set; }
        public Nullable<double> total_qty { get; set; }
        public int doc_no_run { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public Nullable<double> pro_totalamt { get; set; }
        public Nullable<double> avg_qty { get; set; }
        public Nullable<double> avg_cost { get; set; }
        public Nullable<int> ar_doc_no_run { get; set; }
        public Nullable<int> DATE_REPORT { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public string change_avg { get; set; }
        public string docref_no { get; set; }
        public string dealercode { get; set; }
    }
}
