//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Addrbill
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string cus_type { get; set; }
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_soi { get; set; }
        public string add_trog { get; set; }
        public string add_road { get; set; }
        public string add_amphur { get; set; }
        public string add_tumbol { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string add_date { get; set; }
        public string PRE_NAME { get; set; }
        public string tax_id { get; set; }
        public string tax_branch_id { get; set; }
        public string tax_branch { get; set; }
        public string dealercode { get; set; }
    }
}
