//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Arheader_Web_Log
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_type { get; set; }
        public string cus_paycode { get; set; }
        public string cus_code_org { get; set; }
        public string cus_code { get; set; }
        public string invoice_type { get; set; }
        public string member_code { get; set; }
        public string ref_jobmem { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public Nullable<double> car_mileage { get; set; }
        public string ref_branchno { get; set; }
        public string ref_doccode { get; set; }
        public string ref_docno { get; set; }
        public string docref_no { get; set; }
        public string docref_date { get; set; }
        public string payment_duedate { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> ar_prodamt { get; set; }
        public Nullable<double> ar_servamt { get; set; }
        public Nullable<double> ar_amt { get; set; }
        public Nullable<double> ar_disamt { get; set; }
        public Nullable<double> ar_netamt { get; set; }
        public Nullable<double> ar_vatamt { get; set; }
        public Nullable<double> ar_totalamt { get; set; }
        public Nullable<double> ar_recamt { get; set; }
        public Nullable<double> ar_payamt { get; set; }
        public Nullable<double> ar_drcramt { get; set; }
        public Nullable<double> ar_taxamt { get; set; }
        public Nullable<double> ar_paycash { get; set; }
        public Nullable<double> ar_paycard { get; set; }
        public Nullable<double> ar_paychq { get; set; }
        public Nullable<double> ar_paydeposit { get; set; }
        public Nullable<double> ar_payother { get; set; }
        public Nullable<double> ar_onacccredit { get; set; }
        public Nullable<double> ar_writeup { get; set; }
        public Nullable<double> ar_writeoff { get; set; }
        public Nullable<double> ar_payown { get; set; }
        public Nullable<double> ar_directdebit { get; set; }
        public Nullable<double> ar_paytot { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string doc_candate { get; set; }
        public string disputed { get; set; }
        public string receipt_flag { get; set; }
        public Nullable<int> detail_line { get; set; }
        public Nullable<int> print_no { get; set; }
        public string rec_memo { get; set; }
        public string discount_memo { get; set; }
        public Nullable<double> ar_pmamt { get; set; }
        public string user_id { get; set; }
        public string statement_no { get; set; }
        public Nullable<double> ar_payonacccredit { get; set; }
        public Nullable<double> credit_charge_percen { get; set; }
        public Nullable<int> credit_charge_amt { get; set; }
        public string dep_branch { get; set; }
        public string dep_code { get; set; }
        public string dep_no { get; set; }
        public string emp_code { get; set; }
        public string AF_Status { get; set; }
        public string doc_no2 { get; set; }
        public string FULL_PAYDATE { get; set; }
        public string FLAG_NET { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<double> cust_limit { get; set; }
        public Nullable<double> cust_balance { get; set; }
        public string pcc_docno { get; set; }
        public string warranty_date { get; set; }
        public string voidno { get; set; }
        public string PRINT_WARRANTY { get; set; }
        public Nullable<int> NUM_PRINT_WARRANTY { get; set; }
        public string doc_payment { get; set; }
        public string docno_ref { get; set; }
        public string docno_refdate { get; set; }
        public string car_reg_tail { get; set; }
        public Nullable<int> car_tail_mileage { get; set; }
        public Nullable<double> car_tail_avg { get; set; }
        public string ST_RPADETAIL_FLAG { get; set; }
        public string ST_RCPHeader_FLAG { get; set; }
        public string ST_RDPHeader_FLAG { get; set; }
        public string ST_Rdisc_Head_FLAG { get; set; }
        public string ST_BILDetail_FLAG { get; set; }
        public string RZ_FLAG { get; set; }
        public string Warranty_FLAG { get; set; }
        public string Last_edit_date { get; set; }
        public string icard_id { get; set; }
        public string dealercode { get; set; }
        public string Branch_name { get; set; }
        public Nullable<int> record_total { get; set; }
        public string Last_Update { get; set; }
        public string Flag_card_add { get; set; }
        public string Flag_nocard_add { get; set; }
        public string Flag_card_add_date { get; set; }
        public string Flag_nocard_add_date { get; set; }
        public string Pay_PayCard_FLAG { get; set; }
        public string Pay_PayCash_FLAG { get; set; }
        public string Pay_PayCashCard_FLAG { get; set; }
        public string Pay_PayChq_FLAG { get; set; }
        public string Pay_PayDep_FLAG { get; set; }
        public string Pay_Paydoc_FLAG { get; set; }
        public string Pay_PayOnAcc_FLAG { get; set; }
        public string Pay_PayOther_FLAG { get; set; }
        public string Pay_RPADETAIL_FLAG { get; set; }
        public Nullable<double> sum_store_qty { get; set; }
        public Nullable<double> car_avg { get; set; }
        public Nullable<double> km_perday { get; set; }
        public Nullable<int> print_total { get; set; }
        public string flag_net_tb { get; set; }
        public string car_chasis_tail { get; set; }
        public Nullable<int> car_btail_mileage { get; set; }
        public Nullable<int> km_tail_perday { get; set; }
        public Nullable<int> km_tail_permonth { get; set; }
        public string last_tail_contdate { get; set; }
        public string flag_fleet { get; set; }
        public string cuscont_code { get; set; }
        public string coupon_id { get; set; }
        public string config_tyre { get; set; }
        public Nullable<int> docref_date_report { get; set; }
        public string rec_memo2 { get; set; }
        public string doc_canmemo { get; set; }
        public string Bill_Status { get; set; }
        public string Flag_Vat_Transfer { get; set; }
        public string Update_Vat_Transfer { get; set; }
        public string flag_hq { get; set; }
        public string abbref_no { get; set; }
        public string inoref_no { get; set; }
        public Nullable<int> approve_status_id { get; set; }
        public Nullable<int> approve_ok_user_id { get; set; }
        public string approve_ok_date { get; set; }
        public string approve_ok_time { get; set; }
        public string web_log_send_to { get; set; }
        public Nullable<int> web_log_user_id { get; set; }
        public string web_log_date { get; set; }
        public string web_log_time { get; set; }
        public Nullable<int> web_log_flag_send { get; set; }
        public string web_log_message { get; set; }
    }
}
