//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Banktrans
    {
        public int DOC_NO_RUN { get; set; }
        public string branch_no { get; set; }
        public string trans_type { get; set; }
        public Nullable<int> trans_no { get; set; }
        public string trans_date { get; set; }
        public Nullable<int> trans_ref { get; set; }
        public string bankacc_code { get; set; }
        public string bank_code { get; set; }
        public string branch { get; set; }
        public string cq_code { get; set; }
        public string cq_desciption { get; set; }
        public Nullable<double> cq_amount { get; set; }
        public string cq_no { get; set; }
        public string cq_date { get; set; }
        public string clearing_date { get; set; }
        public string trans_status { get; set; }
        public Nullable<double> total_amount { get; set; }
        public string trans_remark { get; set; }
        public string doc_no { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<double> CLEAR_DATE_REPORT { get; set; }
        public Nullable<double> TRAN_DATE_REPORT { get; set; }
        public string ref_chq_no { get; set; }
        public string chq_cancel { get; set; }
        public string chq_cancel_date { get; set; }
        public string chq_cancel_time { get; set; }
        public Nullable<int> cancel_user_id { get; set; }
        public string trans_type_memo { get; set; }
        public string dealercode { get; set; }
    }
}
