//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ChkTemp
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public int doc_no_run { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public Nullable<int> line_no { get; set; }
        public Nullable<int> check_id { get; set; }
        public string check_name { get; set; }
        public string check_product_1 { get; set; }
        public string check_product_2 { get; set; }
        public string check_product_3 { get; set; }
        public Nullable<double> check_price { get; set; }
        public string check_pass { get; set; }
        public string check_comment { get; set; }
        public string dealercode { get; set; }
    }
}
