//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CarGlass
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string car_reg { get; set; }
        public Nullable<int> car_provid { get; set; }
        public string main_pro_code { get; set; }
        public string sub_pro_code { get; set; }
        public Nullable<int> unit_buy { get; set; }
        public Nullable<int> num_of_services { get; set; }
        public string doc_no_buy { get; set; }
        public string doc_no_used { get; set; }
        public string date_buy { get; set; }
        public string time_buy { get; set; }
        public string start_date { get; set; }
        public string expire_date { get; set; }
        public string day_used { get; set; }
        public string date_used { get; set; }
        public string time_used { get; set; }
        public Nullable<int> date_buy_report { get; set; }
        public Nullable<int> start_date_report { get; set; }
        public Nullable<int> expire_date_report { get; set; }
        public Nullable<int> date_used_report { get; set; }
        public string dealercode { get; set; }
    }
}
