//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CommDetail
    {
        public int doc_no_run { get; set; }
        public string doc_no { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> type_commission_id { get; set; }
        public Nullable<double> work_rate { get; set; }
        public Nullable<double> day_of_work { get; set; }
        public Nullable<double> total_rate { get; set; }
        public Nullable<double> ot_rate { get; set; }
        public Nullable<double> hour_of_ot { get; set; }
        public Nullable<double> total_ot { get; set; }
        public Nullable<double> special_rate { get; set; }
        public Nullable<double> day_of_special { get; set; }
        public Nullable<double> total_special { get; set; }
        public Nullable<double> incentive_rate { get; set; }
        public Nullable<double> bonus_rate { get; set; }
        public Nullable<double> other_rate { get; set; }
        public Nullable<double> total_rate_all { get; set; }
        public Nullable<double> total_comm_all { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public Nullable<double> sub_incentive { get; set; }
        public Nullable<double> sub_claim { get; set; }
        public Nullable<double> sub_social_insurance { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
