//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CheckStock_Transaction
    {
        public int id_run { get; set; }
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public Nullable<int> locat_code { get; set; }
        public Nullable<int> last_store_qty { get; set; }
        public Nullable<int> last_real_qty { get; set; }
        public Nullable<int> last_diff_qty { get; set; }
        public Nullable<System.DateTime> last_date_check { get; set; }
        public string last_doc_no { get; set; }
        public Nullable<int> flag_check { get; set; }
    }
}
