//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Claim_Online
    {
        public int id { get; set; }
        public string icard_id { get; set; }
        public string car_reg { get; set; }
        public string car_prov_name { get; set; }
        public string car_brand_name { get; set; }
        public string car_model_name { get; set; }
        public string car_color { get; set; }
        public string pre_name { get; set; }
        public string cus_name { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_trog { get; set; }
        public string add_soi { get; set; }
        public string add_road { get; set; }
        public string add_tambol { get; set; }
        public string add_amphur { get; set; }
        public string add_provname { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string pro_name { get; set; }
        public string pro_serial1 { get; set; }
        public string pro_serial2 { get; set; }
        public string pro_serial3 { get; set; }
        public string pro_serial4 { get; set; }
        public string pro_serial5 { get; set; }
        public string void_no { get; set; }
        public string warranty_date { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
    }
}
