//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Cancel_icard
    {
        public int id { get; set; }
        public string branch_no { get; set; }
        public string dealercode { get; set; }
        public string branch_name { get; set; }
        public string icard_id { get; set; }
        public string register_date { get; set; }
        public string expire_date { get; set; }
        public string car_reg { get; set; }
        public Nullable<int> car_provid { get; set; }
        public string car_prov_name { get; set; }
        public string cus_code { get; set; }
        public string cancel_name { get; set; }
        public string other_detail { get; set; }
        public string cancel_date { get; set; }
        public string cancel_time { get; set; }
        public Nullable<int> cancel_user_id { get; set; }
        public string ip_address { get; set; }
        public string flag_net { get; set; }
        public string last_update { get; set; }
    }
}
