//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CkHeader
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public int doc_no_run { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string car_reg { get; set; }
        public Nullable<int> car_provid { get; set; }
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public string car_brand { get; set; }
        public string car_model { get; set; }
        public string user_receive { get; set; }
        public string user_check { get; set; }
        public string checklist_status { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string rec_memo { get; set; }
        public string edit_date { get; set; }
        public string edit_time { get; set; }
        public Nullable<int> date_report { get; set; }
        public string dealercode { get; set; }
        public string check_set_id { get; set; }
        public string check_name { get; set; }
    }
}
