//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Car_reg
    {
        public int id { get; set; }
        public string flag_net { get; set; }
        public string car_reg { get; set; }
        public string car_province { get; set; }
        public string car_reg_new { get; set; }
        public string Dealercode { get; set; }
        public string Branch_no { get; set; }
        public string Branch_name { get; set; }
        public string car_prov_name_new { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string Last_Update { get; set; }
    }
}
