//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_DayStart
    {
        public int run_id { get; set; }
        public Nullable<System.DateTime> day_start { get; set; }
        public Nullable<decimal> money_default { get; set; }
        public Nullable<int> blue_card_batch_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> computer_id { get; set; }
    }
}
