//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_DayEnd_DocState
    {
        public int ds_id { get; set; }
        public string doc_code { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public Nullable<int> date_report { get; set; }
        public string date_used { get; set; }
        public string date_used_report { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string doc_no_dayend { get; set; }
    }
}
