//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ICARD_EXPIRE
    {
        public int id { get; set; }
        public string icard_id { get; set; }
        public string car_reg { get; set; }
        public Nullable<int> car_provid { get; set; }
        public string cus_code { get; set; }
        public string register_date { get; set; }
        public string expire_date { get; set; }
        public string Last_Update { get; set; }
        public string Dealercode { get; set; }
        public string Branch_no { get; set; }
        public string Branch_name { get; set; }
        public string car_prov_name { get; set; }
        public string FLAG_NET { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
    }
}
