//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ICAApprove_Log
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string app_docno { get; set; }
        public string doc_no { get; set; }
        public Nullable<int> app_user_id { get; set; }
        public string app_date { get; set; }
        public string app_time { get; set; }
        public string ip_address { get; set; }
        public string approve_store_qty { get; set; }
        public string admin_store_qty { get; set; }
        public string admin_store_qty_memo { get; set; }
        public string dealercode { get; set; }
    }
}
