//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Jobdetail_Approve
    {
        public int doc_no_run { get; set; }
        public string app_docno { get; set; }
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public string doc_no { get; set; }
        public int Line_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_type { get; set; }
        public string cus_paytype { get; set; }
        public string cus_code { get; set; }
        public string car_registration { get; set; }
        public string pro_name { get; set; }
        public string store_unit { get; set; }
        public string tran_unit { get; set; }
        public Nullable<double> tran_ratio { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string location_code { get; set; }
        public string io_by { get; set; }
        public Nullable<double> tran_qty { get; set; }
        public Nullable<double> store_qty { get; set; }
        public Nullable<double> receive_qty { get; set; }
        public Nullable<double> pro_costamt { get; set; }
        public Nullable<double> pro_nincludevat { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_amtlasted { get; set; }
        public Nullable<double> pro_disp1 { get; set; }
        public Nullable<double> pro_disp2 { get; set; }
        public Nullable<double> pro_disamt { get; set; }
        public Nullable<double> pro_distotamt { get; set; }
        public Nullable<double> pro_amt { get; set; }
        public string bill_start { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string doc_candate { get; set; }
        public string rec_memo { get; set; }
        public string pm_code { get; set; }
        public string io_type { get; set; }
        public Nullable<int> ref_branchno { get; set; }
        public string ref_doccode { get; set; }
        public string ref_dono { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public string date_services { get; set; }
        public Nullable<double> CAR_NEXTMILEAGE { get; set; }
        public Nullable<double> pro_avg_vat { get; set; }
        public Nullable<double> pro_avg_novat { get; set; }
        public string dealercode { get; set; }
    }
}
