//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Job3Day_LOG
    {
        public int id { get; set; }
        public string Branch_no { get; set; }
        public string Doc_no { get; set; }
        public string Doc_Date { get; set; }
        public string Doc_Time { get; set; }
        public string Call_Memo { get; set; }
        public string Call_Status { get; set; }
        public string Call_Point { get; set; }
        public string Miss_Call_Num { get; set; }
        public string Call_Date { get; set; }
        public string Call_Time { get; set; }
        public string Call_User { get; set; }
        public Nullable<int> Call_UserID { get; set; }
        public string Call_IP { get; set; }
        public Nullable<int> Call_DATE_REPORT { get; set; }
        public string dealercode { get; set; }
    }
}
