//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Jobheader_Approve
    {
        public string app_docno { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public int doc_no_run { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_type { get; set; }
        public string cus_code { get; set; }
        public string member_code { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public Nullable<int> car_mileage { get; set; }
        public string car_bcontact { get; set; }
        public Nullable<int> car_bmileage { get; set; }
        public Nullable<double> car_balance { get; set; }
        public Nullable<double> cust_balance { get; set; }
        public string job_contact { get; set; }
        public string job_conttel { get; set; }
        public string ref_jobmem { get; set; }
        public string ref_branchno { get; set; }
        public string ref_doccode { get; set; }
        public string ref_docno { get; set; }
        public string job_detail { get; set; }
        public string reception_by { get; set; }
        public string mechanic_by { get; set; }
        public string qc_by { get; set; }
        public string invoice_type { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> job_amt { get; set; }
        public Nullable<double> job_discpercent { get; set; }
        public Nullable<double> job_discountamt { get; set; }
        public Nullable<double> job_netamt { get; set; }
        public Nullable<double> job_vatamt { get; set; }
        public Nullable<double> job_totalamt { get; set; }
        public Nullable<double> job_payamt { get; set; }
        public Nullable<double> job_paydeposit { get; set; }
        public Nullable<double> job_paytotal { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string doc_candate { get; set; }
        public string doc_canmemo { get; set; }
        public Nullable<int> detail_line { get; set; }
        public Nullable<int> print_no { get; set; }
        public string rec_memo { get; set; }
        public string job_pmamt { get; set; }
        public string user_id { get; set; }
        public string job_prodamt { get; set; }
        public string job_servamt { get; set; }
        public string test_by { get; set; }
        public string return_by { get; set; }
        public string appoint_fdate { get; set; }
        public string appoint_ftime { get; set; }
        public Nullable<int> appoint_count { get; set; }
        public string appoint_ldate { get; set; }
        public string appoint_ltime { get; set; }
        public string finish_date { get; set; }
        public string finish_time { get; set; }
        public string return_date { get; set; }
        public string return_time { get; set; }
        public string close_date { get; set; }
        public string close_time { get; set; }
        public string job_status { get; set; }
        public Nullable<int> km_perday { get; set; }
        public Nullable<int> km_permonth { get; set; }
        public string ccp_create { get; set; }
        public string ccp_status { get; set; }
        public string type_amt { get; set; }
        public string AF_Status { get; set; }
        public Nullable<double> Car_Avg { get; set; }
        public string CALL_STATUS { get; set; }
        public string CALL_MEMO { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public string meeting_id { get; set; }
        public string CALL_POINT { get; set; }
        public string MISS_CALL_NUM { get; set; }
        public string priceown_code { get; set; }
        public Nullable<double> cust_limit { get; set; }
        public string pcc_docno { get; set; }
        public string docno_ref { get; set; }
        public string docno_refdate { get; set; }
        public string car_reg_tail { get; set; }
        public string car_chasis_tail { get; set; }
        public Nullable<int> car_tail_mileage { get; set; }
        public Nullable<int> car_btail_mileage { get; set; }
        public Nullable<int> km_tail_perday { get; set; }
        public Nullable<int> km_tail_permonth { get; set; }
        public Nullable<double> car_tail_avg { get; set; }
        public string last_tail_contdate { get; set; }
        public string sale_docno { get; set; }
        public string sale_docrefdate { get; set; }
        public string approve_cust_limit { get; set; }
        public string approve_cust_term { get; set; }
        public string approve_sale_limit { get; set; }
        public string approve_avg_cost { get; set; }
        public Nullable<double> cust_limit_new { get; set; }
        public Nullable<double> cust_term { get; set; }
        public Nullable<double> cust_term_old { get; set; }
        public Nullable<double> sale_credit_limit { get; set; }
        public Nullable<double> sale_credit_limit_old { get; set; }
        public Nullable<int> sale_id { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public string admin_cust_limit { get; set; }
        public string admin_cust_term { get; set; }
        public string admin_sale_limit { get; set; }
        public string admin_avg_cost { get; set; }
        public string app_date { get; set; }
        public string app_time { get; set; }
        public string ip_address { get; set; }
        public string admin_cust_limit_memo { get; set; }
        public string admin_cust_term_memo { get; set; }
        public string admin_sale_limit_memo { get; set; }
        public string admin_avg_cost_memo { get; set; }
        public string app_user_id { get; set; }
        public Nullable<int> APP_DATE_REPORT { get; set; }
        public Nullable<int> Approve_1 { get; set; }
        public Nullable<int> Approve_2 { get; set; }
        public Nullable<int> Approve_3 { get; set; }
        public Nullable<int> Approve_4 { get; set; }
        public string config_tyre { get; set; }
        public string dealercode { get; set; }
    }
}
