//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Job3Day_Question
    {
        public int id { get; set; }
        public string Branch_no { get; set; }
        public string Doc_no { get; set; }
        public string Doc_Date { get; set; }
        public string Doc_Time { get; set; }
        public Nullable<int> Question_choice_id { get; set; }
        public string Question_choice_value { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public Nullable<int> Question_UserID { get; set; }
        public string Question_IP { get; set; }
        public string dealercode { get; set; }
    }
}
