//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Logupdate_Data
    {
        public int logupdate_seq { get; set; }
        public string po_log_id { get; set; }
        public string logupdate_typetransfer { get; set; }
        public string doc_id { get; set; }
        public string branch_no { get; set; }
        public string dealercode { get; set; }
        public string doc_type { get; set; }
        public string logupdate_type { get; set; }
        public string logupdate_status { get; set; }
        public string logupdate_note { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_user { get; set; }
    }
}
