//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_LogEdc
    {
        public int edc_log_id { get; set; }
        public string DocNo { get; set; }
        public string receive_edc { get; set; }
        public string Amount { get; set; }
        public string ProCode { get; set; }
        public string PortNo { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
