//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Poheader
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string dealercode { get; set; }
        public int doc_no_run { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string pr_doccode { get; set; }
        public string pr_docno { get; set; }
        public string docref_no { get; set; }
        public string docref_date { get; set; }
        public string ven_code { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<int> ship_to { get; set; }
        public string ship_date { get; set; }
        public Nullable<double> po_amt { get; set; }
        public Nullable<double> po_dispercent { get; set; }
        public Nullable<double> po_discamt { get; set; }
        public Nullable<double> po_netamt { get; set; }
        public Nullable<double> po_vatamt { get; set; }
        public Nullable<double> po_totalamt { get; set; }
        public string po_close { get; set; }
        public string po_cancel { get; set; }
        public string po_status { get; set; }
        public Nullable<int> po_laslineno { get; set; }
        public Nullable<int> count_dtl { get; set; }
        public string AF_Status { get; set; }
        public string po_by { get; set; }
        public string rec_memo { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<double> ven_limit { get; set; }
        public Nullable<double> ven_balance { get; set; }
        public string po_cancel_qty { get; set; }
        public string po_close_cancel_qty { get; set; }
        public Nullable<int> approve_status_id { get; set; }
        public Nullable<int> approve_ok_user_id { get; set; }
        public string approve_ok_date { get; set; }
        public string approve_ok_time { get; set; }
        public Nullable<int> approve_waiting_user_id { get; set; }
        public string approve_waiting_date { get; set; }
        public string approve_waiting_time { get; set; }
        public Nullable<int> approve_reject_user_id { get; set; }
        public string approve_reject_date { get; set; }
        public string approve_reject_time { get; set; }
        public string flag_hq_create { get; set; }
        public Nullable<int> flag_recal_approve { get; set; }
        public string doc_canmemo { get; set; }
        public string rec_memo_in { get; set; }
        public string ven_name { get; set; }
    }
}
