//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_PayCard_Log
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string type_trans { get; set; }
        public string doc_no { get; set; }
        public string temp_doc_no { get; set; }
        public string doc_code { get; set; }
        public string cus_code { get; set; }
        public string Response_Text { get; set; }
        public string Merchant_name_and_Address { get; set; }
        public string Transaction_Date { get; set; }
        public string Transaction_Time { get; set; }
        public string Approval_Code { get; set; }
        public string Invoice_Number { get; set; }
        public string Terminal_ID { get; set; }
        public string Merchant_ID { get; set; }
        public string Card_Issuer_Name { get; set; }
        public string Card_Number { get; set; }
        public string Card_Expiry_Date { get; set; }
        public string Batch_Number { get; set; }
        public string Reference_Number { get; set; }
        public string Card_Issuer_ID { get; set; }
        public string Card_Holder_Name { get; set; }
        public string Amount { get; set; }
        public string Redeem_Point { get; set; }
        public string Redeem_Amount { get; set; }
        public string Redeem_Point_Balance { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_TAX_ID { get; set; }
        public string Customer_Branch_Number { get; set; }
        public string Customer_Car_License { get; set; }
        public string TI { get; set; }
        public string PTT_Blue_Card_Number { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public string add_date { get; set; }
        public string add_time { get; set; }
        public string ip_address { get; set; }
        public string flag_settlement { get; set; }
        public Nullable<int> settlement_user_id { get; set; }
        public string settlement_date { get; set; }
        public string settiement_time { get; set; }
        public string dealercode { get; set; }
        public string doc_no_ref { get; set; }
    }
}
