//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_proserial
    {
        public int DOC_NO_RUN { get; set; }
        public string branch_no { get; set; }
        public string doc_code { get; set; }
        public string pro_code { get; set; }
        public string pro_serial { get; set; }
        public string doc_no { get; set; }
        public string cus_code { get; set; }
        public Nullable<int> line_no { get; set; }
        public string doc_date { get; set; }
        public Nullable<int> warantee_day { get; set; }
        public string exp_date { get; set; }
        public string rec_memo { get; set; }
        public string FLAG_NET { get; set; }
        public string icard_id { get; set; }
        public string Dealercode { get; set; }
        public string Branch_name { get; set; }
        public string Last_Update { get; set; }
    }
}
