//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Paydoc
    {
        public int DOC_NO_RUN { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string rf_docno { get; set; }
        public string doc_code { get; set; }
        public string cus_code { get; set; }
        public Nullable<int> line_no { get; set; }
        public string doc_date { get; set; }
        public string rf_bran { get; set; }
        public string rf_doccode { get; set; }
        public Nullable<double> doc_amt { get; set; }
        public Nullable<double> doc_bal { get; set; }
        public Nullable<double> doc_payamt { get; set; }
        public string rec_memo { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public Nullable<int> user_pay_id { get; set; }
        public string dealercode { get; set; }
    }
}
