//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Proserial_TB
    {
        public int DOC_NO_RUN { get; set; }
        public string branch_no { get; set; }
        public string pro_code { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public Nullable<int> warantee_day { get; set; }
        public string expire_date { get; set; }
        public string pro_serial { get; set; }
        public string wind_tyre { get; set; }
        public string deep_tyre { get; set; }
        public string valve_cover_status { get; set; }
        public string recamic_serial { get; set; }
        public string rec_memo { get; set; }
        public string FLAG_NET { get; set; }
        public string flag_net_tb { get; set; }
        public string Dealercode { get; set; }
        public string Branch_name { get; set; }
        public string icard_id { get; set; }
        public string Last_Update { get; set; }
        public string doc_code { get; set; }
        public Nullable<int> line_no { get; set; }
        public Nullable<int> locat_code { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_disp1 { get; set; }
        public Nullable<double> pro_disp2 { get; set; }
        public Nullable<double> pro_disamt { get; set; }
        public Nullable<double> pro_distotamt { get; set; }
        public Nullable<double> pro_amt { get; set; }
    }
}
