//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_qr_05_ini_product
    {
        public long doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string doc_code { get; set; }
        public string ven_code { get; set; }
        public string pro_code { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> store_qty { get; set; }
        public Nullable<double> pro_price { get; set; }
        public Nullable<double> pro_price_vat { get; set; }
        public Nullable<double> pro_price_before_vat { get; set; }
        public string dealercode { get; set; }
    }
}
