//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_RETURNTEMP
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_code { get; set; }
        public string pro_code { get; set; }
        public string pro_name { get; set; }
        public string serial_no { get; set; }
        public Nullable<double> line_no { get; set; }
        public Nullable<double> store_qty { get; set; }
        public string claim_date { get; set; }
        public string clear_date { get; set; }
        public string due_date { get; set; }
        public string rec_memo { get; set; }
        public int doc_no_run { get; set; }
        public string tyre_position { get; set; }
        public string rec_detail { get; set; }
        public string rec_other_detail { get; set; }
        public string lost_detail { get; set; }
        public string lost_other_detail { get; set; }
        public string ven_code { get; set; }
        public string vendor_date { get; set; }
        public Nullable<int> vendor_date_report { get; set; }
        public string claim_close_date { get; set; }
        public Nullable<int> claim_close_date_report { get; set; }
        public string claim_result { get; set; }
        public string claim_detail { get; set; }
        public string dealercode { get; set; }
    }
}
