//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_RDADetail
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string cus_code { get; set; }
        public string doc_code { get; set; }
        public string dp_name { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public Nullable<double> dp_price { get; set; }
        public string rec_memo { get; set; }
        public string emp_code { get; set; }
        public int DOC_NO_RUN { get; set; }
        public string dealercode { get; set; }
        public string pro_code { get; set; }
        public Nullable<double> dep_qty { get; set; }
        public Nullable<double> sum_price { get; set; }
        public Nullable<double> dep_percent { get; set; }
        public Nullable<double> pro_price { get; set; }
    }
}
