//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_RETURNHEADER_Web_Log
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_no2 { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_code { get; set; }
        public string car_reg { get; set; }
        public string car_prov_name { get; set; }
        public string icard_id { get; set; }
        public string comment { get; set; }
        public string roadside { get; set; }
        public string warranty_date { get; set; }
        public string warranty_axa_id { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public int doc_no_run { get; set; }
        public string flag_net { get; set; }
        public string car_mileage { get; set; }
        public string warranty_mileage { get; set; }
        public string dealercode { get; set; }
        public string Branch_name { get; set; }
        public Nullable<int> record_total { get; set; }
        public string Last_Update { get; set; }
        public string web_log_send_to { get; set; }
        public Nullable<int> web_log_user_id { get; set; }
        public string web_log_date { get; set; }
        public string web_log_time { get; set; }
        public Nullable<int> web_log_flag_send { get; set; }
        public string web_log_message { get; set; }
    }
}
