//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Services
    {
        public int DOC_NO_RUN { get; set; }
        public string branch_no { get; set; }
        public string car_reg { get; set; }
        public string cus_code { get; set; }
        public string pro_code { get; set; }
        public string prosub_code { get; set; }
        public string pro_tname { get; set; }
        public string prosub_name { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public Nullable<double> km_per_day { get; set; }
        public string date_services { get; set; }
        public string FLAG_USED { get; set; }
        public string REF_DOCNO { get; set; }
        public Nullable<double> NUM_ZIGZAG { get; set; }
        public Nullable<double> CAR_NEXTMILE { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
        public string Dealercode { get; set; }
        public string FLAG_NET { get; set; }
        public string Last_Update { get; set; }
        public string car_chasis { get; set; }
    }
}
