//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_SERVICES_CHECK
    {
        public int ID { get; set; }
        public string branch_no { get; set; }
        public string car_reg { get; set; }
        public string cus_code { get; set; }
        public Nullable<double> num_odd { get; set; }
        public string dealercode { get; set; }
    }
}
