//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_SCARD_HEAD_TB
    {
        public int ID { get; set; }
        public string DealerCode { get; set; }
        public string branch_no { get; set; }
        public string Branch_Name { get; set; }
        public string icard_id { get; set; }
        public string cus_id { get; set; }
        public string cus_carid { get; set; }
        public string cus_code { get; set; }
        public string cus_name { get; set; }
        public string car_reg { get; set; }
        public string card_password { get; set; }
        public string add_tel { get; set; }
        public string add_fax { get; set; }
        public string add_name { get; set; }
        public string add_road { get; set; }
        public string add_tumbol { get; set; }
        public string add_amphur { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string car_prov_name { get; set; }
        public string car_body { get; set; }
        public string car_engine { get; set; }
        public string car_engine_cc { get; set; }
        public string car_regdate { get; set; }
        public string car_type_name { get; set; }
        public string car_brand_name { get; set; }
        public string car_model_name { get; set; }
        public string car_color { get; set; }
        public string car_year { get; set; }
        public string car_fdate { get; set; }
        public string last_contdate { get; set; }
        public string first_mileage { get; set; }
        public string last_mileage { get; set; }
        public string register_date { get; set; }
        public string point_all { get; set; }
        public string expire_date { get; set; }
        public string FLAG_NET { get; set; }
        public string add_mobile { get; set; }
        public string add_no { get; set; }
        public string cus_birth { get; set; }
        public Nullable<double> car_average { get; set; }
        public string pre_name { get; set; }
        public string add_moo { get; set; }
        public string add_trog { get; set; }
        public string add_soi { get; set; }
        public string add_email { get; set; }
        public string cus_sex { get; set; }
        public string cus_buss_name { get; set; }
        public string cuscont_name_eng { get; set; }
        public string work_company { get; set; }
        public string work_type1 { get; set; }
        public string work_type2 { get; set; }
        public string work_type3 { get; set; }
        public string work_type4 { get; set; }
        public string work_type5 { get; set; }
        public string work_type5_detail { get; set; }
        public string work_position { get; set; }
        public string work_section { get; set; }
        public string work_tower { get; set; }
        public string work_floor { get; set; }
        public string work_no { get; set; }
        public string work_soi { get; set; }
        public string work_road { get; set; }
        public string work_tumbol { get; set; }
        public string work_amphur { get; set; }
        public string work_province { get; set; }
        public string work_zipcode { get; set; }
        public string work_phone { get; set; }
        public string work_phone2 { get; set; }
        public string work_fax { get; set; }
        public string work_email { get; set; }
        public string type_newsletter1 { get; set; }
        public string type_newsletter2 { get; set; }
        public string type_newsletter3 { get; set; }
        public string type_newsletter4 { get; set; }
        public string type_newsletter5 { get; set; }
        public string cus_edit_date { get; set; }
        public string car_detail1 { get; set; }
        public string car_detail2 { get; set; }
        public string car_detail3 { get; set; }
        public string car_work1 { get; set; }
        public string car_work2 { get; set; }
        public string car_work3 { get; set; }
        public string car_work3_detail { get; set; }
        public string car_work4 { get; set; }
        public string car_work4_detail { get; set; }
        public string car_edit_date { get; set; }
        public string add_tel_ext { get; set; }
        public string add_tel2 { get; set; }
        public string add_tel2_ext { get; set; }
        public string add_tel3 { get; set; }
        public string add_tel3_ext { get; set; }
        public string add_fax_ext { get; set; }
        public string add_mobile2 { get; set; }
        public string work_moo { get; set; }
        public string work_trog { get; set; }
        public string work_fax2 { get; set; }
        public string work_phone3 { get; set; }
        public string work_phone4 { get; set; }
        public string work_mobile { get; set; }
        public string work_mobile2 { get; set; }
        public Nullable<int> add_provid { get; set; }
        public Nullable<int> add_tambol_id { get; set; }
        public Nullable<int> add_amphur_id { get; set; }
        public Nullable<int> work_provid { get; set; }
        public Nullable<int> work_tambol_id { get; set; }
        public Nullable<int> work_amphur_id { get; set; }
        public string TB_Customer_type { get; set; }
        public string TB_Customer_code { get; set; }
        public Nullable<double> TB_Customer_point { get; set; }
        public string flag_net_tb { get; set; }
        public string Last_Update { get; set; }
    }
}
