//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_TRNHeader
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string dealercode { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public Nullable<int> ven_code { get; set; }
        public string ref_branchno { get; set; }
        public string ref_doccode { get; set; }
        public string ref_docno { get; set; }
        public string docref_no { get; set; }
        public string docref_date { get; set; }
        public string type_update { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string doc_candate { get; set; }
        public string to_dealercode { get; set; }
        public Nullable<int> date_report { get; set; }
        public string bill_novat_status { get; set; }
        public string rec_memo { get; set; }
        public string doc_canmemo { get; set; }
        public Nullable<double> total_amt { get; set; }
        public string trn_status { get; set; }
        public Nullable<int> trn_in_user_id { get; set; }
        public string trn_in_status_date { get; set; }
        public string trn_in_status_time { get; set; }
        public Nullable<int> trn_in_status_date_report { get; set; }
        public Nullable<int> trn_reject_user_id { get; set; }
        public string trn_reject_status_date { get; set; }
        public string trn_reject_status_time { get; set; }
        public Nullable<int> trn_reject_status_date_report { get; set; }
        public string docref_dealercode { get; set; }
        public string from_dealercode { get; set; }
        public string trn_from_status { get; set; }
        public string trn_to_status { get; set; }
        public Nullable<int> trn_receive_user_id { get; set; }
        public string trn_receive_status_date { get; set; }
        public string trn_receive_status_time { get; set; }
        public Nullable<int> trn_receive_status_date_report { get; set; }
        public Nullable<int> trn_waiting_user_id { get; set; }
        public string trn_waiting_status_date { get; set; }
        public string trn_waiting_status_time { get; set; }
        public Nullable<int> trn_waiting_status_date_report { get; set; }
    }
}
