//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Transfer_Data_Log
    {
        public int id { get; set; }
        public string type { get; set; }
        public string table { get; set; }
        public string txt_schema { get; set; }
        public Nullable<int> rows_affected { get; set; }
        public Nullable<bool> status { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
