//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_UpdateHeader
    {
        public string branch_no { get; set; }
        public string doc_code { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string ref_branchno { get; set; }
        public string ref_doccode { get; set; }
        public string ref_docno { get; set; }
        public string docref_date { get; set; }
        public string docref_no { get; set; }
        public string emp_code { get; set; }
        public string vat_type { get; set; }
        public Nullable<double> vat_rate { get; set; }
        public Nullable<double> ar_prodamt { get; set; }
        public Nullable<double> ar_amt { get; set; }
        public Nullable<double> ar_disamt { get; set; }
        public Nullable<double> ar_vatamt { get; set; }
        public Nullable<double> ar_totalamt { get; set; }
        public string doc_close { get; set; }
        public string doc_cancel { get; set; }
        public string doc_candate { get; set; }
        public Nullable<int> detail_line { get; set; }
        public Nullable<int> print_no { get; set; }
        public string rec_memo { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string dealercode { get; set; }
    }
}
