//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Voidno_Del_Log
    {
        public int id { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string branch_name { get; set; }
        public string icard_id { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string cus_code { get; set; }
        public string car_reg { get; set; }
        public string car_chasis { get; set; }
        public string voidno { get; set; }
        public string warranty_date { get; set; }
        public string delete_date { get; set; }
        public string delete_time { get; set; }
        public string sUserName { get; set; }
        public string ip_address { get; set; }
        public string flag_net { get; set; }
    }
}
