//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_WTHDetail
    {
        public int doc_no_run { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string income1_rate_name { get; set; }
        public Nullable<double> income1_rate { get; set; }
        public Nullable<double> income1_amt { get; set; }
        public Nullable<double> income1_vatamt { get; set; }
        public string income2_rate_name { get; set; }
        public Nullable<double> income2_rate { get; set; }
        public Nullable<double> income2_amt { get; set; }
        public Nullable<double> income2_vatamt { get; set; }
        public string income3_rate_name { get; set; }
        public Nullable<double> income3_rate { get; set; }
        public Nullable<double> income3_amt { get; set; }
        public Nullable<double> income3_vatamt { get; set; }
        public string income4_rate_name { get; set; }
        public Nullable<double> income4_rate { get; set; }
        public Nullable<double> income4_amt { get; set; }
        public Nullable<double> income4_vatamt { get; set; }
        public string income4_2_rate_name { get; set; }
        public Nullable<double> income4_2_1_1_rate { get; set; }
        public Nullable<double> income4_2_1_1_amt { get; set; }
        public Nullable<double> income4_2_1_1_vatamt { get; set; }
        public Nullable<double> income4_2_1_2_rate { get; set; }
        public Nullable<double> income4_2_1_2_amt { get; set; }
        public Nullable<double> income4_2_1_2_vatamt { get; set; }
        public Nullable<double> income4_2_1_3_rate { get; set; }
        public Nullable<double> income4_2_1_3_amt { get; set; }
        public Nullable<double> income4_2_1_3_vatamt { get; set; }
        public string income4_2_1_4_rate_other { get; set; }
        public Nullable<double> income4_2_1_4_rate { get; set; }
        public Nullable<double> income4_2_1_4_amt { get; set; }
        public Nullable<double> income4_2_1_4_vatamt { get; set; }
        public Nullable<double> income4_2_2_rate { get; set; }
        public Nullable<double> income4_2_2_amt { get; set; }
        public Nullable<double> income4_2_2_vatamt { get; set; }
        public Nullable<double> income4_2_3_rate { get; set; }
        public Nullable<double> income4_2_3_amt { get; set; }
        public Nullable<double> income4_2_3_vatamt { get; set; }
        public string income5_rate_name { get; set; }
        public Nullable<double> income5_rate { get; set; }
        public Nullable<double> income5_amt { get; set; }
        public Nullable<double> income5_vatamt { get; set; }
        public string income6_rate_name { get; set; }
        public Nullable<double> income6_rate { get; set; }
        public Nullable<double> income6_amt { get; set; }
        public Nullable<double> income6_vatamt { get; set; }
        public string dealercode { get; set; }
    }
}
