//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCS_ITEM
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string SN_ID { get; set; }
        public string SN2_ID { get; set; }
        public Nullable<int> line_No { get; set; }
        public string pro_code { get; set; }
        public string pro_ven_code { get; set; }
        public string locat_code { get; set; }
        public string sRepairID { get; set; }
        public string sClamID { get; set; }
        public Nullable<int> nlot { get; set; }
        public Nullable<decimal> nDiff { get; set; }
        public string pro_code_new { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<decimal> pro_disamt { get; set; }
        public string sRemark { get; set; }
        public string sn_ID_close { get; set; }
        public string sn_ID_cancle { get; set; }
        public string doc_code { get; set; }
        public string doc_no_ref { get; set; }
    }
}
