//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCS_location
    {
        public int locat_code { get; set; }
        public string locat_name { get; set; }
        public string novat_status { get; set; }
        public string AF_Status { get; set; }
        public string show_status { get; set; }
        public string BRANCH_NO { get; set; }
    }
}
