//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_Data
    {
        public int Transfer_ID { get; set; }
        public string Source_Table { get; set; }
        public string Source_Field { get; set; }
        public string Source_Key { get; set; }
        public string Destination_Table { get; set; }
        public string Destination_Field { get; set; }
        public string Destination_Key { get; set; }
        public string WebService_Function { get; set; }
        public string Data_Type { get; set; }
        public string Log_Table { get; set; }
        public string Log_Field { get; set; }
    }
}
