//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Cash_Drawer
    {
        public string bankacc_code { get; set; }
        public string bankacc_id { get; set; }
        public string bankacc_name { get; set; }
        public string bank_code { get; set; }
        public string bank_branch { get; set; }
        public Nullable<double> open_balance { get; set; }
        public string open_date { get; set; }
        public Nullable<double> current_balance { get; set; }
        public string current_date { get; set; }
        public string bankacc_type { get; set; }
        public string date_type { get; set; }
        public string bankacc_remark { get; set; }
        public string dealercode { get; set; }
        public string branch_no { get; set; }
        public string Cash_Drawer_Date { get; set; }
        public string Expr1 { get; set; }
        public string SempNo { get; set; }
        public Nullable<double> Cash_Drawer_Balace { get; set; }
        public string Cash_Drawer_Type_Name { get; set; }
        public string Cash_Drawer_Detail { get; set; }
        public string Cash_Drawer_Doc_Ref { get; set; }
        public Nullable<double> Cash_Drawer_Amount { get; set; }
        public string Cash_Drawer_Remark { get; set; }
    }
}
