//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CD
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string SEmpNo { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string cus_code { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public string date_report { get; set; }
        public string cus_name { get; set; }
        public string SN_ID { get; set; }
        public string pro_code { get; set; }
        public string SN2_ID { get; set; }
        public Nullable<decimal> nDiff { get; set; }
        public Nullable<int> nlot { get; set; }
        public string locat_code { get; set; }
        public string pro_code_new { get; set; }
        public string sRepairID { get; set; }
        public string sClamID { get; set; }
        public string sn_ID_close { get; set; }
        public string sn_ID_cancle { get; set; }
        public string doc_no_ref { get; set; }
        public string doc_time { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string cd_Remark { get; set; }
        public string csRemCancle { get; set; }
        public Nullable<double> cd_distotalamt { get; set; }
        public Nullable<double> cd_netamt { get; set; }
        public Nullable<double> cd_vatamt { get; set; }
        public Nullable<double> cd_totalamt { get; set; }
    }
}
