//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GDT_RPT
    {
        public string hbranch_no { get; set; }
        public string hdoc_no { get; set; }
        public string hdoc_code { get; set; }
        public string hdoc_date { get; set; }
        public string hdoc_time { get; set; }
        public string hven_code { get; set; }
        public string hpay_date { get; set; }
        public string hemp_code { get; set; }
        public string hdoc_ref_no1 { get; set; }
        public string hdoc_Ref_date1 { get; set; }
        public string hdoc_ref_no2 { get; set; }
        public string hdoc_Ref_date2 { get; set; }
        public string hvate_type { get; set; }
        public Nullable<double> hvate_rate { get; set; }
        public Nullable<double> hsd_disamt { get; set; }
        public Nullable<double> hsd_dispercent { get; set; }
        public Nullable<double> hsd_distotalamt { get; set; }
        public Nullable<double> hsd_netamt { get; set; }
        public Nullable<double> hsd_vatamt { get; set; }
        public Nullable<double> hsd_totalamt { get; set; }
        public string hsd_Remark { get; set; }
        public string hsd_payment { get; set; }
        public Nullable<double> hsd_paycash { get; set; }
        public Nullable<double> hsd_paycard { get; set; }
        public Nullable<double> hsd_paydeposite { get; set; }
        public Nullable<double> hsd_payother { get; set; }
        public Nullable<double> hsd_paytot { get; set; }
        public string hdoc_Close { get; set; }
        public string hdoc_Cancle { get; set; }
        public string hdoc_cancledate { get; set; }
        public Nullable<double> hven_limit { get; set; }
        public Nullable<double> hven_balance { get; set; }
        public Nullable<int> hdate_report { get; set; }
        public Nullable<int> hdetail_line { get; set; }
        public string hdoc_no2 { get; set; }
        public string hsd_CcRemark { get; set; }
        public string hdoc_ref { get; set; }
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public Nullable<decimal> line_No { get; set; }
        public string pro_code { get; set; }
        public string doc_code { get; set; }
        public string doc_time { get; set; }
        public string doc_date { get; set; }
        public string pro_name { get; set; }
        public string pro_ven_code { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public Nullable<double> store_qty { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<decimal> pro_amt { get; set; }
        public string pro_code_close { get; set; }
        public string pro_code_cancle { get; set; }
        public string pro_code_cancle_date { get; set; }
        public string ven_code { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string SN2_ID { get; set; }
        public string SN_ID { get; set; }
        public string SN_pro_code_new { get; set; }
        public Nullable<int> nlot { get; set; }
        public string reduce_no { get; set; }
        public string pro_code_new { get; set; }
        public Nullable<decimal> nDeep_Tyre { get; set; }
        public string cStatus { get; set; }
        public string repair_remark { get; set; }
        public string reduce_remark { get; set; }
        public string clam_remark { get; set; }
        public string product_Remark { get; set; }
        public string sn_ID_close { get; set; }
        public string sn_ID_cancle { get; set; }
        public Nullable<decimal> doc_no_run { get; set; }
        public string doc_ref_no { get; set; }
        public Nullable<decimal> pro_disamt { get; set; }
        public string Width_Face { get; set; }
        public string pro_tname { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public string pro_brand { get; set; }
        public string progroup_code { get; set; }
        public string Expr1 { get; set; }
        public string pro_size { get; set; }
    }
}
