//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Get_AllowedCoupon
    {
        public Nullable<int> group_coupon_id { get; set; }
        public string give_product_group_code { get; set; }
        public string give_progroup_code { get; set; }
        public string give_pro_brand_code { get; set; }
        public string promotion_give_code { get; set; }
        public Nullable<int> prod_brandcode { get; set; }
        public Nullable<int> product_group_code { get; set; }
        public string pmdproduct_group_code { get; set; }
        public string promotion_detail_code { get; set; }
        public string doc_no { get; set; }
        public string pro_id { get; set; }
        public string coupon_group_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<decimal> coupon_value_amount { get; set; }
        public Nullable<decimal> coupon_value_percent { get; set; }
        public string coupon_code { get; set; }
        public string coupon_name { get; set; }
        public string progroup_code { get; set; }
        public string custype_code { get; set; }
        public Nullable<int> pro_give_type_id { get; set; }
        public Nullable<bool> pro_give_product_same { get; set; }
        public string product_code { get; set; }
        public Nullable<int> pro_give_type_detail { get; set; }
        public Nullable<int> pro_price_id { get; set; }
        public Nullable<double> pro_price_total { get; set; }
        public Nullable<double> store_qty { get; set; }
    }
}
