//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Moveserial4
    {
        public int smenu { get; set; }
        public string branch_no { get; set; }
        public string doc_code { get; set; }
        public string doc_name { get; set; }
        public string doc_date { get; set; }
        public string date_report { get; set; }
        public string doc_no { get; set; }
        public string cus_name { get; set; }
        public string locat_code { get; set; }
        public string pro_code { get; set; }
        public string sdoc_no_ref { get; set; }
        public string doc_time { get; set; }
        public string SN_ID { get; set; }
        public string sn2_ID { get; set; }
        public string sn_ID_close { get; set; }
        public string sn_ID_cancle { get; set; }
    }
}
