//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RCT_SD
    {
        public string doc_no { get; set; }
        public string doc_no_sd { get; set; }
        public string branch_no { get; set; }
        public string SEmpNo { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string cus_code { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public Nullable<int> date_report { get; set; }
        public string cus_name { get; set; }
        public string SN_ID { get; set; }
        public string pro_code { get; set; }
        public string SN2_ID { get; set; }
        public Nullable<decimal> nDiff { get; set; }
        public Nullable<int> nlot { get; set; }
        public string pro_code_new { get; set; }
        public string sRepairID { get; set; }
        public string sClamID { get; set; }
        public string sn_ID_close { get; set; }
        public string sn_ID_cancle { get; set; }
        public string locat_name { get; set; }
        public string pro_tname { get; set; }
        public string pro_ven_code { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string store_qty { get; set; }
        public string rpt { get; set; }
        public string unit_name { get; set; }
        public Nullable<double> average_cost { get; set; }
        public Nullable<double> lasted_cost { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string novat_status { get; set; }
    }
}
