//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RCT_rpt
    {
        public string hbranch_no { get; set; }
        public string hdoc_no { get; set; }
        public string hSEmpNo { get; set; }
        public string hdoc_code { get; set; }
        public string hdoc_date { get; set; }
        public string hdoc_time { get; set; }
        public string hcus_code { get; set; }
        public string hpay_date { get; set; }
        public string hvate_type { get; set; }
        public Nullable<double> hvate_rate { get; set; }
        public Nullable<double> hcd_disamt { get; set; }
        public Nullable<double> hcd_dispercent { get; set; }
        public Nullable<double> hcd_distotalamt { get; set; }
        public Nullable<double> hcd_netamt { get; set; }
        public Nullable<double> hcd_vatamt { get; set; }
        public Nullable<double> hcd_totalamt { get; set; }
        public string hcd_Remark { get; set; }
        public string hcd_payment { get; set; }
        public Nullable<double> hcd_paycash { get; set; }
        public Nullable<double> hcd_paycard { get; set; }
        public Nullable<double> hcd_paydeposite { get; set; }
        public Nullable<double> hcd_payother { get; set; }
        public Nullable<double> hcd_paytot { get; set; }
        public string hdoc_Close { get; set; }
        public string hdoc_Cancle { get; set; }
        public string hdoc_cancledate { get; set; }
        public Nullable<double> hcus_limit { get; set; }
        public Nullable<double> hcus_balance { get; set; }
        public string hdate_report { get; set; }
        public Nullable<int> hdetail_line { get; set; }
        public string hdoc_no2 { get; set; }
        public string hdoc_inv_clam { get; set; }
        public string hdoc_ref_no { get; set; }
        public string hcsRemCancle { get; set; }
        public string dpro_code { get; set; }
        public Nullable<int> dsale_unit_code { get; set; }
        public string dpro_name { get; set; }
        public string dpro_ven_code { get; set; }
        public Nullable<double> dstore_qty { get; set; }
        public Nullable<decimal> dpro_price { get; set; }
        public Nullable<decimal> dpro_distotamt { get; set; }
        public Nullable<decimal> dpro_amt { get; set; }
        public string dpro_code_close { get; set; }
        public string dpro_code_cancle { get; set; }
        public string dpro_code_cancle_date { get; set; }
        public string dprogroup_code { get; set; }
        public string dpro_brand { get; set; }
        public string dpro_model { get; set; }
        public string ddoc_no_ref { get; set; }
        public string iSN_ID { get; set; }
        public string iSN2_ID { get; set; }
        public string ilocat_code { get; set; }
        public string isRepairID { get; set; }
        public string isClamID { get; set; }
        public Nullable<int> inlot { get; set; }
        public Nullable<decimal> inDiff { get; set; }
        public string ipro_code_new { get; set; }
        public Nullable<decimal> ipro_price { get; set; }
        public Nullable<decimal> ipro_disamt { get; set; }
        public string isRemark { get; set; }
        public string isn_ID_close { get; set; }
        public string isn_ID_cancle { get; set; }
        public string idoc_code { get; set; }
        public string idoc_no_ref { get; set; }
        public Nullable<int> pro_size_code { get; set; }
        public string size_name { get; set; }
        public string pro_size { get; set; }
        public string cuscont_name { get; set; }
    }
}
