//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SD
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string ven_code { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public Nullable<int> detail_line { get; set; }
        public string pro_code { get; set; }
        public string SN_ID { get; set; }
        public string SN2_ID { get; set; }
        public string ven_name { get; set; }
        public Nullable<int> date_report { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string sn_ID_cancle { get; set; }
        public string doc_time { get; set; }
        public string sn_ID_close { get; set; }
    }
}
