//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SDT_RPT
    {
        public string hbranch_no { get; set; }
        public string hdoc_no { get; set; }
        public string hdoc_code { get; set; }
        public string hdoc_date { get; set; }
        public string hdoc_time { get; set; }
        public string hven_code { get; set; }
        public string hemp_code { get; set; }
        public string hdoc_Close { get; set; }
        public string hdoc_Cancle { get; set; }
        public string hdoc_cancledate { get; set; }
        public string hdate_report { get; set; }
        public Nullable<int> hdetail_line { get; set; }
        public string hdoc_no2 { get; set; }
        public string hsRemark { get; set; }
        public string hsCcRemark { get; set; }
        public string dbranch_no { get; set; }
        public string ddoc_no { get; set; }
        public Nullable<int> dline_No { get; set; }
        public string dpro_code { get; set; }
        public string ddoc_code { get; set; }
        public string ddoc_date { get; set; }
        public string ddoc_time { get; set; }
        public string dpro_name { get; set; }
        public string dpro_ven_code { get; set; }
        public Nullable<int> dsale_unit_code { get; set; }
        public Nullable<double> dstore_qty { get; set; }
        public string dven_code { get; set; }
        public Nullable<int> dlocat_code { get; set; }
        public string dSN_ID { get; set; }
        public string dSN2_ID { get; set; }
        public string dpro_code_new { get; set; }
        public Nullable<int> dnlot { get; set; }
        public Nullable<decimal> dnDeep_tyre { get; set; }
        public string dsn_ID_cancle { get; set; }
        public string dsn_ID_close { get; set; }
        public Nullable<int> ddoc_no_run { get; set; }
        public string ddoc_ref_no { get; set; }
        public string dDOT { get; set; }
        public string dSN_REMARK { get; set; }
        public string vVen_name { get; set; }
        public Nullable<int> ppro_brand_code { get; set; }
        public string bpro_brand { get; set; }
        public string progroup_code { get; set; }
        public string pType { get; set; }
        public string pro_size { get; set; }
    }
}
