//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SD_rpt
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string ven_code { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public Nullable<int> detail_line { get; set; }
        public string pro_code { get; set; }
        public string SN_ID { get; set; }
        public string SN2_ID { get; set; }
        public string ven_name { get; set; }
        public Nullable<int> date_report { get; set; }
        public Nullable<int> locat_code { get; set; }
        public string sn_ID_cancle { get; set; }
        public string doc_time { get; set; }
        public string sn_ID_close { get; set; }
        public string ds_doc_ref_no { get; set; }
        public string sRepairID { get; set; }
        public string sClamID { get; set; }
        public string sRepairName { get; set; }
        public string sClamName { get; set; }
        public Nullable<double> store_qty { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public Nullable<decimal> pro_amt { get; set; }
        public string reduce_no { get; set; }
        public string cStatus { get; set; }
        public Nullable<decimal> nDeep_Tyre { get; set; }
        public string pro_code_new { get; set; }
        public string repair_remark { get; set; }
        public string clam_remark { get; set; }
        public string reduce_remark { get; set; }
        public string product_Remark { get; set; }
        public string doc_ref_no { get; set; }
        public Nullable<decimal> pro_disamt { get; set; }
        public string emp_code { get; set; }
        public string vate_type { get; set; }
        public Nullable<double> vate_rate { get; set; }
        public Nullable<double> sd_disamt { get; set; }
        public Nullable<double> sd_dispercent { get; set; }
        public Nullable<double> sd_distotalamt { get; set; }
        public Nullable<double> sd_netamt { get; set; }
        public Nullable<double> sd_vatamt { get; set; }
        public Nullable<double> sd_totalamt { get; set; }
        public string sd_Remark { get; set; }
        public string doc_cancledate { get; set; }
        public Nullable<double> ven_balance { get; set; }
        public string sd_CcRemark { get; set; }
        public string pro_name { get; set; }
        public string SN_pro_code_new { get; set; }
        public Nullable<int> nlot { get; set; }
        public string locat_name { get; set; }
    }
}
