//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFndProd4CD002
    {
        public Nullable<int> ncount { get; set; }
        public string pro_code { get; set; }
        public string ven_code { get; set; }
        public string pro_tname { get; set; }
        public string progroup_code { get; set; }
        public string progroup_name { get; set; }
        public Nullable<int> pro_brand_code { get; set; }
        public Nullable<int> pro_model_code { get; set; }
        public string pro_model { get; set; }
        public string size_name { get; set; }
        public Nullable<double> pro_ohqty { get; set; }
        public string prosub_code { get; set; }
        public string pro_brand { get; set; }
        public Nullable<int> unit_code { get; set; }
        public Nullable<double> lasted_cost { get; set; }
        public string stock_status { get; set; }
        public Nullable<double> pro_ohqty_cs { get; set; }
        public string doc_no { get; set; }
        public string branch_no { get; set; }
    }
}
