//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string branch_no { get; set; }
        public string doc_no { get; set; }
        public string SEmpNo { get; set; }
        public string doc_code { get; set; }
        public string doc_date { get; set; }
        public string doc_time { get; set; }
        public string cus_code { get; set; }
        public string doc_Close { get; set; }
        public string doc_Cancle { get; set; }
        public string pro_code { get; set; }
        public Nullable<int> sale_unit_code { get; set; }
        public string pro_name { get; set; }
        public Nullable<decimal> pro_amt { get; set; }
        public string SN_ID { get; set; }
        public string SN2_ID { get; set; }
        public string locat_code { get; set; }
        public Nullable<int> nlot { get; set; }
    }
}
