//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vote_link_customer
    {
        public string branch_no { get; set; }
        public string cus_code { get; set; }
        public int cus_code_run { get; set; }
        public string cus_type { get; set; }
        public string custype_code { get; set; }
        public string buss_code { get; set; }
        public string cus_paytype { get; set; }
        public string pre_name { get; set; }
        public string cus_name { get; set; }
        public string cuscont_name { get; set; }
        public string add_name { get; set; }
        public string add_no { get; set; }
        public string add_moo { get; set; }
        public string add_soi { get; set; }
        public string add_trog { get; set; }
        public string add_road { get; set; }
        public string add_tumbol { get; set; }
        public string add_amphur { get; set; }
        public Nullable<short> add_provid { get; set; }
        public string add_province { get; set; }
        public string add_zip { get; set; }
        public string add_tel { get; set; }
        public string add_mobile { get; set; }
        public string add_fax { get; set; }
        public string add_email { get; set; }
        public string cusgroup_code { get; set; }
        public string cus_member { get; set; }
        public Nullable<double> pro_discount { get; set; }
        public Nullable<double> lab_discount { get; set; }
        public Nullable<double> cust_discount { get; set; }
        public Nullable<int> vat_code { get; set; }
        public Nullable<double> pay_method { get; set; }
        public Nullable<double> credit_term_code { get; set; }
        public Nullable<double> credit_term { get; set; }
        public Nullable<double> credit_limit { get; set; }
        public Nullable<double> credit_bal { get; set; }
        public string contact_fdate { get; set; }
        public string contact_ldate { get; set; }
        public string cancel_date { get; set; }
        public string behavior_memo { get; set; }
        public string rec_memo { get; set; }
        public string on_acccredit { get; set; }
        public string cus_birth { get; set; }
        public string cus_sex { get; set; }
        public string discount_type { get; set; }
        public string deposit_amount { get; set; }
        public string af_status { get; set; }
        public Nullable<double> DATE_REPORT { get; set; }
    }
}
