//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSmart_MerchantTerminalSetting
    {
        public int ProductLevelID { get; set; }
        public int ComputerID { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public int TimeForInputDataInTextBox { get; set; }
        public byte CanInputCardByTelephone { get; set; }
    }
}
