//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSmart_OrderDiscountData
    {
        public int POS_TransactionID { get; set; }
        public int POS_ComputerID { get; set; }
        public int DiscountID { get; set; }
        public string Code { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public byte TenderTypeID { get; set; }
        public decimal Qty_Used { get; set; }
        public decimal Qty_Balance { get; set; }
        public decimal Qty_Return { get; set; }
        public decimal Price_Used { get; set; }
        public decimal Price_Balance { get; set; }
        public decimal Price_Return { get; set; }
        public string Other { get; set; }
    }
}
