//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSmart_OrderMaster
    {
        public int POS_TransactionID { get; set; }
        public int POS_ComputerID { get; set; }
        public int POS_SessionID { get; set; }
        public int POS_SessionComputerID { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public int Batch_ID { get; set; }
        public int Stand_ID { get; set; }
        public decimal TRN_Price { get; set; }
        public decimal TRN_Point { get; set; }
        public int Redeem_Trans_ID { get; set; }
        public decimal Redeem_Price { get; set; }
        public decimal Net_Price { get; set; }
        public string Payment_Type { get; set; }
        public string Card_No { get; set; }
        public string Phone_No { get; set; }
        public long Trans_ID { get; set; }
        public decimal Point_Earn_Today { get; set; }
        public decimal Return_Point { get; set; }
        public string Customer_Name { get; set; }
        public decimal Point_Balance { get; set; }
        public string PR_Message { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public int TransactionStatusID { get; set; }
        public string Company_Type { get; set; }
        public string Business_Type { get; set; }
        public string Day_Trn_Limit { get; set; }
        public string Month_Trn_Limit { get; set; }
        public string Year_Trn_Limit { get; set; }
        public string U_Limit { get; set; }
        public string Slip_Message_1 { get; set; }
        public string Slip_Message_2 { get; set; }
        public string Slip_Message_3 { get; set; }
        public byte IsPTTCoBrand { get; set; }
        public string BlueCode { get; set; }
        public decimal Net_PriceBeforeDiscount { get; set; }
        public string Invoice_ID { get; set; }
        public string SaleModeName { get; set; }
        public string Redemption_ID { get; set; }
        public string EarnPointByType { get; set; }
    }
}
