//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSmart_RedeemMasterFront
    {
        public int POS_TransactionID { get; set; }
        public int POS_ComputerID { get; set; }
        public int POS_SessionID { get; set; }
        public int POS_SessionComputerID { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public int Batch_ID { get; set; }
        public int Stand_ID { get; set; }
        public decimal TRN_Point { get; set; }
        public string Card_No { get; set; }
        public string Phone_No { get; set; }
        public long Trans_ID { get; set; }
        public decimal POS_PaymentAmount { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public int TransactionStatusID { get; set; }
        public string BlueCode { get; set; }
        public decimal Point_Balance { get; set; }
        public string Redemption_ID { get; set; }
        public string EarnPointByType { get; set; }
        public byte RedeemStatus { get; set; }
        public int RedeemID { get; set; }
    }
}
