//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSmart_RedeemInfo
    {
        public int doc_no_run { get; set; }
        public int TransactionID { get; set; }
        public int ComputerID { get; set; }
        public decimal TotalRedeemPoint { get; set; }
        public decimal PaymentAmount { get; set; }
        public string VSmartProductCode { get; set; }
        public decimal RedeemPoint { get; set; }
        public decimal PerPaymentAmount { get; set; }
        public string RedeemNote { get; set; }
        public int RedeemID { get; set; }
        public byte RedeemStatus { get; set; }
    }
}
