//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSmart_SlipAdInfoDetail
    {
        public int POS_TransactionID { get; set; }
        public int POS_ComputerID { get; set; }
        public int SlipID { get; set; }
        public int SlipOrderID { get; set; }
        public string TypeAd { get; set; }
        public string SlipText { get; set; }
    }
}
